### ISSUE TITLE
Headroom and iOS: Alternative fixes to the scroll inertia lag?

### ISSUE THREAD

**Issue by mhulse** [WickyNilliams/headroom.js#100]
> [iOS doesn't fire scroll events as other browsers do, it debounces the event for you. This is a little annoying as headroom is less responsive this way, but it does still work.](https://github.com/WickyNilliams/headroom.js/issues/54#issuecomment-42456148)

Just out of curiosity, any ideas on how to make Headroom more iOS "scroll friendly"?

How about alternative solutions?

Here's a site that has a "Headroom"-esque header:

http://newrelic.com/

For mobile, looks like they turn off the JS and make the header static. Not a bad solution.

Thoughts anyone? What have others done? What would be the simplest way to disable Headroom based on mobile/touch detection?

**Comment by lelis718** [comment]
Cordova apps still uses legacy WebView in ios and the hangfire is buggy in this platform.
