### ISSUE TITLE
Detect bottom of page

### ISSUE THREAD

**Issue by vicpuntnl** [WickyNilliams/headroom.js#108]
Like mentioned on twitter:

Would be nice to have detection when you reached the bottom of the page, and then toggle classnames 'headroom--not-bottom' / 'headroom--bottom'.

**Comment by ogrosko** [comment]
+1

**Comment by WickyNilliams** [comment]
This might be useful, yes. @jackyon i don't think I'll add an option for autoshow, as that can be handled with the proposed solution of adding a new class

**Comment by gandhiShepard** [comment]
This would be a fantastic addition! Until then I've been hacking away at this: http://alexcican.com/post/teehan-lax-navigation/

**Comment by richgcook** [comment]
+1

**Comment by Jore** [comment]
+1
