### ISSUE TITLE
Safari both Windows and Mac not working

### ISSUE THREAD

**Issue by bozhidargeorgiev** [WickyNilliams/headroom.js#112]
It works great so far on Firefox, IE, Chrome but it doesn't even initiate the plugin on Safari for both WIn and Mac.
Any thoughts?!

**Comment by saulia** [comment]
Hi I am having a problem with safari on a mac, header flies to the left, becomes vertical and then settles at the top, it is very annoying for the user.  I have tried on 4 different macs and it is the same in all, any help on how to resolve this would be greatly appreciated.

**Comment by WickyNilliams** [comment]
It works fine on my mac. Can you create a reduced test case so it can be investigated?

**Comment by saulia** [comment]
Sorry what do you mean a reduced test case?

It works on all browsers on my mac except safari, the URL is http://79.170.44.87/lmcd.co.uk/

I have attached a screen grab video where you can see what happens.


Thanks for taking the time to respond

Kind Regards

Brian

**Comment by WickyNilliams** [comment]
A reduced test case is an example where absolutely everything non-essential is stripped away and only your particular issue remains. This is helpful because people often find the actual (often unrelated) cause in the process,  and if not then it makes diagnosis far easier. Typically people will create a jsfiddle or codepen (or any other such service) to demonstrate the issue.

**Comment by saulia** [comment]
Ok Thanks, 

I am not really sure how to go about this.   The headroom.js file as you can see has been included in to an open cart theme that I have purchased from a 3rd party, I am therefore unaware of how to strip this out etc, I have tried unsuccessfully to get the template developer to look at it for me but they don’t seem interested.  Would you be interested in having a look to see if you can fix the issue on a freelance basis?

Did you view the problem on the video I sent through?

Regards

Brian
