### ISSUE TITLE
Responsive headroom resize problem

### ISSUE THREAD

**Issue by jacquesletesson** [WickyNilliams/headroom.js#124]
Hi there,

I'm working with headroom.js and the jquery plugin.

I have a simple resize function to destroy headroom on mobile and activate it on larger screen.

If I load my website on mobile version than squeeze the window to a larger screen the headroom initialisation is never fired. Maybe because the resize event is fired many times. Is there a way of doing this without using a setTimeout ? 

Thanks in advance,

J.

```
$(window).resize(function(){
		winW = document.body.clientWidth;
		winH = document.body.clientHeight;
		m = (winW > b) ? false : true;
		if (m == true){
				$('body').addClass("no-fluid-nav");
				$('body').removeClass("fluid-nav");
				$("#navigation__header").headroom("destroy");
		} else {
				$('body').removeClass("no-fluid-nav");
				$('body').addClass("fluid-nav");
				$("#navigation__header").headroom();
		}
		console.log("Resize");		
	});

**Comment by WickyNilliams** [comment]
matchMedia is probably what you want to use here.

```js
function setupHeadroom(mql) {
  if(mql.matches) {
    $("#navigation__header").headroom();
  }
  else {
    $("#navigation__header").headroom("destroy");
  }
}

var mql = matchMedia(desktopMediaQuery)
mql.addListener(setupHeadroom); //listen for future changes
setupHeadroom(mql); // handle for page load
```

Though be aware that there is an issue with destroy in the jQuery plugin (see #130), so you may want to switch to just using the vanilla Headroom API.

Closing as this isn't a bug
