### ISSUE TITLE
Multiple scrollElement for tabbed lists

### ISSUE THREAD

**Issue by digitaltopo** [WickyNilliams/headroom.js#126]
I'm working on a case where there are 4 tabbed sections, each with a list inside. Each list has it's own scrollbar, so that the scroll position for each list is preserved when jumping between tabs. I've tried to apply headroom to each of these tab containers but it only seems to initialize for one. Is there any way to use headroom on multiple scrollable elements?

Code:

var scrollElement = document.querySelector(".tabs-containers");

$(".fixed-heading").headroom({
	 scroller : scrollElement
});

**Comment by WickyNilliams** [comment]
Hmm not sure how I would support this, it would make things fairly complex I think. Have you tried having a separate headroom instance for each scroll box, passing the same header element to each? e.g.

```js
var scrollers = document.querySelectorAll(".tabs-containers");
var header = document.querySelector(".fixed-heading")

scrollers.forEach(function(scroller) {
   var hr = new Headroom(header, { scroller: scroller });
   hr.init();
})
```

That *might* work. Let me know if you're having the issue still (probably not given how long it's taken me to reply!)

**Comment by WickyNilliams** [comment]
BTW going to close as I don't think this is something I will add support for (at least not at the moment, it's a fairly exotic use case, and nobody else has asked about it)

**Comment by andre-dw** [comment]
I would also like to use this as i'm making an phonegap app with multiple pages and one header above it. I can only make it work on one page now.
