### ISSUE TITLE
.headroom('destroy') isn't

### ISSUE THREAD

**Issue by dmitryleskov** [WickyNilliams/headroom.js#130]
I have `(jQuery.)?headroom.js` included in a common .js file loaded by all pages of a site, followed by a call to `$(selector).headroom(options)`. All good, works great.

I then added a hero block *above* the main menu on the home page and needed to switch Headroom off specifically on that page. However, a simple call to `$(selector).headroom('destroy')` did not work. I tried to re-initialize with huge offset:

    $(selector)
      .headroom('destroy')
      .headroom({offset: 100500})

to no avail. The `destroy()` method does not know anything about jQuery, so it does not remove jQuery data from the element and re-initlaization does not work.

I ended up with the following workaround:

    $(selector)
      .headroom('destroy')
      .removeData('headroom')
      .headroom({offset: 100500})

but it looks dirty.

**Comment by WickyNilliams** [comment]
Hmm yeah, I see what you mean. I guess I'll have to intercept the destroy call in the jQuery plugin and do what you did with `removeData`. I think your approach is fine for now, or you can not use the jQuery plugin and use the standard API

**Comment by proov** [comment]
Hello,

i re-open this issue, is there a way to destroy & relaunch headroom easily ? Once it is destroyed it's over ? ^^

**Comment by bramsmulders** [comment]
@WickyNilliams this is a rather harsh decision, for me it is clear that if you make a wrapper you make all methods available through that wrapper. We now have to work around the problem ourselves, rather than the solution is made by the creator. You even close the bug without any doubt, but the bug is still there. I will try to make a pull request for it this week. 

In the meanwhile i have a workaround that really works:

```js
/**
 * Check if headroom is initialised before and kill it with fire!
 */
if($el.data('headroom')) {
    $el.data('headroom').destroy();
    $el.removeData('headroom');
}
```

This is possible because the jQuery wrapper assignes the Headroom object to data('headroom') and thus the .destroy() function is available through there. We destroy it, and then remove the headroom object from data. After this you can initialise headroom again.

**Comment by WickyNilliams** [comment]
You have a strange definition of harsh. And your tone isn't very polite. Remember open source authors are doing this in their free time, for no cost. Less of a sense of entitlement please. 

I'd just advise, as I have before, using the raw Headroom object. It has a simple API, don't see any problem using it for more advanced cases like this

**Comment by bramsmulders** [comment]
I'm not acting entitled, i presume that code is released with thought. Off-course there are always bugs and if those bugs are reported I, and with me many others, think they must not be ignored. At least leave the bug open just for someone who feels like pull requesting. If your opinion is to just use the raw Headroom object, then why not remove the jQuery(and other) wrappers all together? 

I appreciate the effort others put in open source projects, and I apologise if I came over rather entitled or unpolite.

**Comment by HarrisRobin** [comment]
@bramsmulders thank you for your solution. one thing though, it fails to remove headroom--not-top when destroying if that class already exists. 

However, looks like this issue is known:
https://github.com/WickyNilliams/headroom.js/pull/159

**Comment by WickyNilliams** [comment]
Never mentioned it here explicitly - but I fixed this bug.

@bramsmulders sorry for being a little uppity at the time, reading your comments back I think I misinterpreted your attitude!

**Comment by bramsmulders** [comment]
Hi @WickyNilliams, thnx for the reply. I myself could have been less harsh in my initial response.

**Comment by gt06** [comment]
@bramsmulders I have updated my code which you had given. But nothing happened. I want to destroy headroom for iPhone landscape orientation when hamburger menu is open. Also remove that destroy option as soon as hamburger is close.
