### ISSUE TITLE
function for updating scroller

### ISSUE THREAD

**Issue by dannycochran** [WickyNilliams/headroom.js#141]
for pages with separate scrolling containers, I'd like to switch the headroom scroller depending on what is being scrolled. rather than instantiate a new Headroom for each container, or re-instantiate on scroll, I'd like to update the scroller.

I wrote a function into headroom that I believe does this, but wanted to run it by you before doing a pull request and see if you had thoughts on how to handle this case:
```
updateScroller : function (scroller)  {
     this.destroy();
     this.scroller = scroller;
     this.setupListeners();
},
```

and ```setupListeners()``` takes the functionality out of ```init()``` into a separate, reusable function:
```
setupListeners: function () {
      this.elem.classList.add(this.classes.initial);

      // defer event registration to handle browser 
      // potentially restoring previous scroll position
      setTimeout(this.attachEvent.bind(this), 100);
},
```

and in my view I listen for scroll events and do the following:
```
onScroll: function (e) {
    if (e.currentTarget !== this.headroom.scroller) {
        this.headroom.updateScroller(e.currentTarget);
    },
}

**Comment by WickyNilliams** [comment]
I think it would be easier to just have multiple instances of headroom, which is closer aligned with what you actually want here

**Comment by dannycochran** [comment]
Well I actually want to avoid multiple instances, but I suppose that's just a personal preference.

Headroom is a single purpose function that hides or closes the banner / navbar. Creating multiple instances just replicates that function with an immutable parameter (a scroll container), as opposed to creating just one function which accepts a DOM container as a parameter.
