### ISSUE TITLE
TypeError: this.scroller.addEventListener is not a function

### ISSUE THREAD

**Issue by sachbearbeiter** [WickyNilliams/headroom.js#142]
hi,

i want to use the jquery version of headroom (together with jquery 2.1.3) and get in a local test environment:

TypeError: this.scroller.addEventListener is not a function
...Y=this.getScrollY(),this.initialised=!0,this.scroller.addEventListener("scroll",...

    <html>
    <head>
       <script src="jquery.js"></script> 
       <script src="headroom.min.js"></script> 
       <script src="jQuery.headroom.min.js"></script> 
       <script src="call.js"></script> 
    </head>
    <body>
        <div id="nav">test</div>
    </body>

the call is:

```js
  $( document ).ready(function() {
        $("#nav").headroom(
        {
        // vertical offset in px before element is first unpinned
        offset : 0,
        // scroll tolerance in px before state changes
        tolerance : 0,
        // or you can specify tolerance individually for up/down scroll
        tolerance : {
            up : 5,
            down : 0
        },
        // css classes to apply
        classes : {
            // when element is initialised
            initial : "headroom",
            // when scrolling up
            pinned : "headroom--pinned",
            // when scrolling down
            unpinned : "headroom--unpinned",
            // when above offset
            top : "headroom--top",
            // when below offset
            notTop : "headroom--not-top"
        },
        // element to listen to scroll events on, defaults to `window`
        scroller : 'window',
        // callback when pinned, `this` is headroom object
        onPin : function() {},
        // callback when unpinned, `this` is headroom object
        onUnpin : function() {},
        // callback when above offset, `this` is headroom object
        onTop : function() {},
        // callback when below offset, `this` is headroom object
        onNotTop : function() {},
        });
      });
```

Have you got maybe an idea?

**Comment by WickyNilliams** [comment]
The issue is that you are passing a string as `scroller` option, when it should be a DOM element.

Since you seem to be using the default options, you don't need to set them all manually. The best approach is to start with no options, then add custom ones as needed. Therefore, this should fix your issue:

```js
$("#nav").headroom();
```

**Comment by sachbearbeiter** [comment]
thanks a lot ...
