### ISSUE TITLE
Not work when browse not support requestAnimationFrame.

### ISSUE THREAD

**Issue by bammoo** [WickyNilliams/headroom.js#146]
I find the `init()` just `return` when not support requestAnimationFrame, but the default browser of a China's popular phone brand called Meizu not support requestAnimationFrame. I've notified them about this, but they may take a while to debug and fix this.
So, I think the plugin can make a little change by using `setTimeout` as a fallback?

**Comment by WickyNilliams** [comment]
Just include a requestAnimationFrame polyfill and it should then work fine. The docs cover this :)
