### ISSUE TITLE
AngularJS scroller="" in directive not working.

### ISSUE THREAD

**Issue by digitaltopo** [WickyNilliams/headroom.js#147]
I have an absolutely positioned div with an overflow-y:auto on it. I'd like to add headroom to an element within this div. I can't get the scroller="#scrollingcontainer" to work, instead I get this error:

Error: [jqLite:nosel] Looking up elements via selectors is not supported by jqLite! 

I have included headroom.js  (0.7.0) via bower, and added the dependency:
    <script src="bower_components/headroom.js/dist/headroom.js"></script>
    <script src="bower_components/headroom.js/dist/angular.headroom.js"></script>

angular
.module('app', [
  'headroom',...

In my template I've included the directive:

<div headroom scroller="div#scrollingcontainer">...

I've tried these too:
scroller="#scrollingcontainer"
scroller=".scrollingcontainer" (for class)
for the scrolling container also. 

What am I doing wrong??? It looks pretty clear in the documentation that you need to enter a selector that the directive then uses to get a dom element...

Any help would be appreciated, thanks!

**Comment by WickyNilliams** [comment]
Could you create a reduced test case?

**Comment by zwacky** [comment]
if you're using jqLite only, without jQuery loaded beforehand. you can't look up by selector.

**Comment by zwacky** [comment]
reference #171

**Comment by reco** [comment]
+1

**Comment by shanezheng** [comment]
@digitaltopo @WickyNilliams @zwacky You can't use the selector, instead you need to include the html string.

such as
```html
<headroom tolerance='0' offset='0' scroller="<div class='app-view'></div>" classes="{pinned:'headroom--pinned',unpinned:'headroom--unpinned',initial:'headroom'}"></headroom>
```

**Comment by zwacky** [comment]
why not just use one api as described in the docs (https://github.com/WickyNilliams/headroom.js#with-angularjs). is there a reason why you don't want to use `document.querySelector`?

**Comment by shanezheng** [comment]
@zwacky
A few things:
1. I agree with you. document.querySelector is faster, but document.getElementByid is the fastest. I would say if we want to change it, change to getElementById, and enforce the use to pass the id of the element. Best performance.
2. As a workaround for now, I have to use the code I pasted above.
3. Whether it is a good practice to use document.querySelector or document.getElementById in AngularJS? I am not sure.

**Comment by zwacky** [comment]
you would cut away *a lot* from the versatility if it would need to be used with `getElementById`.

`document.querySelector` is perfectly fine to lookup elements and is very much supported (http://caniuse.com/#search=querySelector). I wouldn't force people to use IDs in their html just for this premature optimization - which can be certainly ignored performance-wise.

nowadays we are more aware of the webapp size, so fewer are running angular with jquery.

**Comment by shanezheng** [comment]
@zwacky Sorry, but the workaround I said before did not work. It dismissed the console error, but the actual functionality is not working, because Angular.element does not select, instead it creates a copy.
Since your Pull request has been there for ever, and nobody merge it, I have to fork this, apply your fix to the fork and get my project to point to my fork. Painful.

**Comment by zwacky** [comment]
i see. lemme update my pull request.

**Comment by zwacky** [comment]
i just checked, there were no commits after this PR.

@WickyNilliams you see any problems with this?

**Comment by WickyNilliams** [comment]
Finally merged this. Sorry for the delay all :)
