### ISSUE TITLE
Custom transitions based on pinned, unpinned, pinned--top

### ISSUE THREAD

**Issue by trangbnguyen** [WickyNilliams/headroom.js#148]
This is not really an issue but something to share with others who want a smoother transition and maybe cut down on some dev time. My client's website header is huge about 90px+ depending elements that are added or removed based on the client's behavior. I had searched the internet and couldn't find anything so I created a solution.

Also, the tolerance did not play nice on iOS8 and older versions of Android, so I set everything to 0 and slowed the up/down with a multi property transition mixin. Different properties would have different transitions.

I ended up creating three custom transitions binding them to
.headroom--pinned.headroom--not-top
.headroom--pinned.headroom--not-top

Here's a fiddle
https://jsfiddle.net/trangbnguyen/mtngc718/40/

Thanks for the JS library!
Trang

**Comment by EnigmaSolved** [comment]
Nice!  Thanks for sharing!  :)

**Comment by WickyNilliams** [comment]
Thanks for the tip. Hopefully will be of use to someone in future
