### ISSUE TITLE
iOS8 Issue when Input is present.

### ISSUE THREAD

**Issue by trangbnguyen** [WickyNilliams/headroom.js#151]
Our header has an input embedded in it. In iOS8, if there is an input present and the user focuses on it, iOS8 scrolls the page back to the top. Whereas Android and iOS7, the page stays in the same place. 

Has anyone else run into this issue?

I recreated this on my site bettycrocker.com. I also recreated it on the headroom site by remote debugging and adding an input into the html. 

Thanks,
Trang

**Comment by WickyNilliams** [comment]
Could you create a reduced test case for this? I don't have the time to do so myself.
