### ISSUE TITLE
Header hidden under Android 4.4.3 url bar

### ISSUE THREAD

**Issue by Mellivora** [WickyNilliams/headroom.js#152]
Hello, thanks very much for your work on this plugin.

In the android 4.4.3 browser on an HTC when I scroll down the page and then scroll back up (when the headroom--not-top class is added) the header drops down but the url bar of the browser also drops down and covers part of the header. It only gets uncovered once I have scrolled back to the top of the page (when the headroom--top class is added).

**Comment by Mellivora** [comment]
Got the same device, HTC One with Android 5.0.2 and this does not happen.

**Comment by WickyNilliams** [comment]
Feels like a browser bug/issue? I assume you're talking about the non-chrome browser?

**Comment by Mellivora** [comment]
Yes, it's the HTC browser (webkit) that came on the phone. Looks like a bug with the specific version as the updated device is working. Brilliant plugin, many thanks!
