### ISSUE TITLE
Supporting multiple initial/top/pinned/unpinned class tokens?

### ISSUE THREAD

**Issue by fritx** [WickyNilliams/headroom.js#157]
```js
{
  // ...
  classes: {
    initial: 'animated hinge',
    // ...
  }
}
```

throws:

```
Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList':
The token provided ('a b') contains HTML space characters, which are not valid in tokens.
```

cause the source code doesn't support multiple class tokens:

```js
this.elem.classList.add(this.classes.initial);
this.elem.classList.remove(classes.unpinned, classes.pinned, classes.top, classes.initial);
```

How about we improving it?

**Comment by WickyNilliams** [comment]
I don't feel there is a real need for this. This is the first time it's been requested since release. It can be worked around by simply merging the multiple CSS classes

**Comment by hacknug** [comment]
There's a need for this if you use utility-based CSS and want to toggle multiple classes depending on Headroom's state.

Would you be open to a PR that introduces the option to pass multiple classes?

**Comment by WickyNilliams** [comment]
@hacknug excuse the delay... yes i'd be open to that

**Comment by hacknug** [comment]
I started looking into this but there a couple way to do it:
- Allow `classes[state]` to be String or Array
- Turn default classes into an array and require always an array

Which one you'd prefer, @WickyNilliams? I'd say the first so it's backwards compatible but maybe the second approach would allow us to simplify the codebase (although minimally)

**Comment by WickyNilliams** [comment]
I'd rather it not be a breaking change, so continuing to support plain ol' strings would be my choice.

Since there are dedicated `addClass`/`removeClass` methods now, this should be pretty easy to add without complicating things much. The only place it might be a bit tricky is `hasClass`. We check classes to determine whether any state (e.g top/bottom) has changed. If we support multiple classes we'd have to check every class is present.

**Comment by WickyNilliams** [comment]
Another option instead of each class being `string | string[]` is to have space-delimited strings for multiple classes. Then we can call `split(" ")` whether it's a single class or multiple, which will result is always having an array which we can `apply`/spread:

```js
  addClass: function(className) {
    this.elem.classList.add.apply(this.elem, this.classes[className].split(" "));
  },
```

Might be simpler that way

**Comment by hacknug** [comment]
Single-string is definitely the best option imho. Less things will change and everything should work pretty much the same.
