### ISSUE TITLE
Mobile Chrome Performance

### ISSUE THREAD

**Issue by Clearnine** [WickyNilliams/headroom.js#166]
This seems to work well on mobile safari, and all the desktop browsers, but on mobile chrome there is a significant delay before actions are taken.  On the same device (iPad Air, iOS 8.3) safari is nearly instant. Will be testing on a nexus device later today.  Interestingly on the Nexus 7 (2012) it's about the same as safari on iOS.  

This is my code  

	$("header").headroom({
		"offset": 125,
		"tolerance": 5,
		"classes": {
			"initial": "",
			"pinned": "pinned",
			"unpinned": "unpinned",
			"top": "top",
        	"notTop": "not-top"
  		}
	});

	header.pinned {
		-webkit-transform: translateY(0%);
		-moz-transform: translateY(0%);
		-ms-transform: translateY(0%);
		-o-transform: translateY(0%);
		transform: translateY(0%);
	}

	header.unpinned {
		-webkit-transform: translateY(-95%);
		-moz-transform: translateY(-95%);
		-ms-transform: translateY(-95%);
		-o-transform: translateY(-95%);
		transform: translateY(-95%);
	}

	header.unpinned:hover {
		transform: translateY(0%);
		border-bottom: none;
	}

	header.not-top{
		background: rgba(51,51,51,.9);
		-webkit-box-shadow: 0px 4px 8px 0px rgba(0, 0, 0, 0.4);
		-moz-box-shadow:    0px 4px 8px 0px rgba(0, 0, 0, 0.4);
		box-shadow:         0px 4px 8px 0px rgba(0, 0, 0, 0.4);
	}

**Comment by Clearnine** [comment]
I now suspect this is simply an issue with Chrome on iOS and not specific to this application, but leaving it open just in case there is some recommendation, etc for chrome on iOS.

**Comment by urfolomeus** [comment]
Unfortunately this is due to how Chrome is currently implemented on iOS. To quote:

"Any iOS app that uses web views — including Facebook, Twitter, and Chrome for iOS — will get the old behavior until they upgrade their apps to WKWebView."

From the excellent [post by TJ VanToll](http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal).

**Comment by WickyNilliams** [comment]
@urfolomeus is correct. This is not bad performance (scrolling is still smooth!), this is due to the way iOS used to handle scroll events, which still persists in webviews it seems. Nothing I can do, sorry
