### ISSUE TITLE
Different offset value on mobile

### ISSUE THREAD

**Issue by kkemila** [WickyNilliams/headroom.js#168]
I would need to have different offset value on mobile devices, because on mobile the menu is the upmost element unlike on desktop. Is this doable?

So basically I need to set different options depending on screen size.

**Comment by WickyNilliams** [comment]
Look at browser's `matchMedia` API. Can run callbacks in response to media queries matching/not matching. Change the offset of the headroom object in the appropriate callback

**Comment by kkemila** [comment]
Thanks! Didn't quite get it working: http://stackoverflow.com/questions/31120755/headroom-js-options-with-enquire-js
