### ISSUE TITLE
headroom not work with jquery.fullPage

### ISSUE THREAD

**Issue by phevose** [WickyNilliams/headroom.js#169]
headroom not work with jquery.fullPage ,when i scroll page,the header class always is "headroom headroom--top",how can i use headroom width jquery.fullPage?
this is my script:

<script src="/javascripts/jquery-1.11.2.min.js"></script>
<script src="/plugin/fullpage/jquery.fullPage.min.js"></script>
<script src="/plugin/slimscroll/jquery.slimscroll.min.js"></script>
<script src="/plugin/headroom/headroom.min.js"></script>
<script>
var myElement = document.querySelector(".header");
var headroom  = new Headroom(myElement);
headroom.init();
$(function() {
	$('#fullpage').fullpage({
		sectionsColor: ['#1bbc9b', '#4BBFC3', '#7BAABE', 'whitesmoke'],
		anchors: ['section1', 'section2', 'section3', 'section4',],
		scrollingSpeed: 700,
		scrollOverflow:true,
		css3:true
	});
});

**Comment by WickyNilliams** [comment]
Sorry to be curt, but I have no idea what jQuery.fullPage is, and you've not shown any code. This seems like an integration issue that is better suited to StackOverflow. Closing
