### ISSUE TITLE
Despite feature checks IE9 displays an error about classList functions

### ISSUE THREAD

**Issue by Jaybuz** [WickyNilliams/headroom.js#170]
When opening the page with Headroom included this error popups in IE9:

```
SCRIPT5007: Unable to get value of the property 'contains': object is null or undefined
```

Somehow IE is running the code before the feature check is run.

**Comment by Jaybuz** [comment]
I've figured it out. It's caused by calling one of the functions. There's no feature check on them.

**Comment by WickyNilliams** [comment]
Yes, you should do the feature check yourself

```js
if(Headroom.cutsTheMustard) {
  // init headroom here
}
```
