### ISSUE TITLE
{ "offset" : a DOM element }?

### ISSUE THREAD

**Issue by leeethe** [WickyNilliams/headroom.js#172]
Can Headroom set "Headroom.options.offset" to a DOM element, as well?
Just like what headhesive.js does:
[headhesive.js](https://github.com/markgoodyear/headhesive.js/blob/master/README.md)
![img](http://ww4.sinaimg.cn/mw690/df1b8fe8gw1eu72cvgqtsj20i8044mxn.jpg)

**Comment by WickyNilliams** [comment]
There's no built-in feature for this, but it's trivial to do. See #176:

```js
var hr = new Headroom(header, {
  offset : someElement.offsetTop
});
```
