### ISSUE TITLE
Responsive headroom with diff functions depending the width

### ISSUE THREAD

**Issue by gabu69** [WickyNilliams/headroom.js#173]
I have a different header depending the width of my page (it has completely different divs) and im trying to get a code to work out when the window is resized:
  
    function headroomrezise(){
	    if ($(window).width() > 927) {
	    	$(".nav-primary").headroom({
	    		"offset": 250,
		    	"tolerance": {
		    		down: 0,
	    			up: 20
			},
			"classes": {
				"initial": "headroom",
				"pinned": "subiendo",
				"unpinned" : "bajando",
				"top": "topando",
				"notTop": "noesarriba"
			}
		});
	}
	else {
		$(".site-header").headroom({
			"offset": 55,
			"tolerance": {
				down: 0,
				up: 20
			},
			"classes": {
				"initial": "headroom",
				"pinned": "subiendo",
				"unpinned" : "bajando",
				"top": "topando",
				"notTop": "noesarriba"
			}
		});
	}
    }
    
    $(document).ready(function() {
        headroomrezise();
        $(window).resize(function() {
            $(".nav-primary").headroom("destroy");
            $(".site-header").headroom("destroy");
            setTimeout(function(){ headroomrezise(); }, 150);  
        });
    });  

But seems when i resize the destroy works but the headroom function isnt adding again the classes properly to my header div, what can I do to fix this?

**Comment by WickyNilliams** [comment]
You'd be better off using `matchMedia`. It handles testing media queries in JS, and allows for listeners so you get an event when a matches or no longer matches. This will give you the hooks to do wht you want

**Comment by gabu69** [comment]
Owwww, im a real amateur in all this, im not even a coder just implemented it under test and error, is there any way you can provide a basic example?

**Comment by WickyNilliams** [comment]
Untested, but something like this:

```js
var headroom;

function createHeadroom(element) {
  headroom = new Headroom(element, {
    "offset": 250,
    "tolerance": {
        down: 0,
        up: 20
    },
    "classes": {
        "initial": "headroom",
        "pinned": "subiendo",
        "unpinned" : "bajando",
        "top": "topando",
        "notTop": "noesarriba"
    }
  });
}

function handleMqChange(mq) {
  if(headroom) {
    headroom.destroy();
  }

  if(mq.matches) {
    createHeadroom(document.querySelector(".nav-primary"))
  }
  else {
    createHeadroom(".site-header");
  }
}

// create media query obj
var mq = matchMedia("(min-width: 927px)");

// when the state of mq changes, call our function
mq.addListener(handleMqChange);

// handle initial load
handleMqChange(mq);
```

I can't help anymore, I'm afraid. I can't field every help request, I simply don't have time

**Comment by gabu69** [comment]
Thanks a lot, that will be enough

**Comment by WickyNilliams** [comment]
I'm not using the jQuery plugin, because it just gets in the way in this case. Easier to just call `destroy` directly on Headroom object

**Comment by WickyNilliams** [comment]
No problem
