### ISSUE TITLE
What if opened header menu is long and needs scrolling?

### ISSUE THREAD

**Issue by opal-digital** [WickyNilliams/headroom.js#177]
Hi,
I'm a self-taught programmer and might not understand if this acutally has been answered before...

My first test using headroom works great, but what if the header contains a menu icon that will open a long menu list that needs to be scrolled – I guess that the script will run again and hide everything.
How to avoid this? Is this one of the situations where I should use something else than "window" to detect scrolling? Is there a tutorial or old post here that can give me some instructions how to do it?
Very happy is you have time to reply to this issue!

**Comment by WickyNilliams** [comment]
Personally, I wouldn't use headroom on a header that contains a big drop down menu, probably not very good ux.

But if you're set on it, in the CSS set a an absolute value for `translateY` instead of a relative value like `100%`. For example, if your header is 100px tall:

```css
.headroom--unpinned {
    transform: translateY(-100px);
}
```
