### ISSUE TITLE
Your instructions don't work on my iPhone, but your demo page does...

### ISSUE THREAD

**Issue by opal-digital** [WickyNilliams/headroom.js#178]
Hi again,
I've tried to follow the instructions I found here:http://wicky.nillia.ms/headroom.js/
Those works on my desktop but not on my iPhone (4).
Your demo page does work in both cases, so I copied your main.css and main.js and this work when I test it. And the combination of your main.css and the headroom.js also works both places. 
The class names and css in the instructions and in the code for your demo page is not the same, and as far as I can see it might be the way of animation that is the big differense – the 'animation', 'sideUp' and 'slideDown' terms makes it work – but your main.css is compiled - one long line of code... so it is difficult for me to see what I need to copy.
Do you have any plans on making a "package" with uncompiled files – based on the demo page?
Love the script – and looks better and have better functions than the other fixed animated menu bar scripts I have seen :-)

**Comment by opal-digital** [comment]
Sorry! 
I did not understand the information "Note: I have omitted any vendor-prefixes for clarity." – that must be the -webkit, -moz and -o stuff on the 'transform'...

**Comment by newbie5402** [comment]
Hi there, 

I was wondering if you were able to resolve this issue?  Even after including the correct vendor-prefixes, headroom.js only worked for me on desktop, but not on iOS 8 for some reason.  Kindly advise!

**Comment by WickyNilliams** [comment]
@newbie5402  It should work in iOS8. Previous versions of iOS are problematic because of they way that scroll events are dispatched by the OS. 

@opal-digital correct, vendor prefixes are stuff like `-webkit`. I omitted them because they are subject to change and don't want to have to keep them up to date.
