### ISSUE TITLE
Scroll up, and then stick as container scrolls off top?

### ISSUE THREAD

**Issue by smlombardi** [WickyNilliams/headroom.js#179]
It's not apparently clear to me if this can be done:

![screen shot 2015-08-12 at 3 40 35 pm](https://cloud.githubusercontent.com/assets/835148/9234877/99b2ffe6-4109-11e5-9bff-4af928cb77ca.png)

User scrolls page (which has the 300px gradient box and 60px bar) up and **under** the top 50px header, sticking to the bottom edge of the top header.  So, when scrolling is done, you just have the 2 bars left?

How would I approach that?  I've tried a few combinations of settings, but my bar always scrolls off.

Note, I have already fixed the top header via other means.  It's fixed permanently.

**Comment by WickyNilliams** [comment]
You would need to measure the distance of the bottom bar from the top of the page, and set that as the offset. Then use the classes which headroom applies to position it correctly (most likely changing is to `position:fixed`)

```js
var bottomBar = document.querySelector(".blah");
var hr  = new Headroom(bottomBar, {
  offset : window.pageYOffset + bottomBar.getBoundingClientRect().top
});
hr.init();
```

You will probably get some kind of "jump" in content where the element has been taken from the flow by fixed positioning. This is something you would have to workaround yourself (probably have a wrapper element which maintains the height of the actual bottom bar, so it doesn't collapse when removed from flow)
