### ISSUE TITLE
Problem with Safari OSX

### ISSUE THREAD

**Issue by MiniHarlock** [WickyNilliams/headroom.js#180]
Hi,

I followed 2 tutorials on the Gantry site (cause I'm working myself on a gantry template for Joomla) as well as the tutorial on your site, to try and insert headroom.js to my site. But I have a terrible feeling of confusion. Some informations seem to be missing or quite unclear. Sorry, but we're not all "specialists"… what is vendor-prefixes ? Are we supposed to add something there or not ? Same question about @import "dependencies".

When we're working locally, the link to the script is mentionned that way on several tutorials :

```html
<script type="text/javascript" src="{{ url(http://gantry-1927.kxcdn.com'gantry-theme://custom/js/headroom.min.js') }}"></script>
```

Should'nt it be :

```html
<script type="text/javascript" src="{{ url('gantry-theme://custom/js/headroom.min.js') }}"></script>
```

?

Are we supposed to add something else to the code you show on your site ? Like -webkit definitions or something ?

Cause here is my problem : in Safari (OSX), whatever the div I target with your script, this div is like sliding form the left FIRST, on each reload of the page. I really don't get it, and I already spent 3 days on this. About to give up… So I did what the tutorials said, over and over again, but I always get this issue. I finally used the simple version of the code, where you have no real (sliding) options, only a fixed menu and I get the same : the div slides from the left at first, really fast, creating some dirty visual effect. Things are OK on my other browsers.

Any idea of what I missed here ?
Many thanks in advance for your help, I'm using my last forces here ! :-)

**Comment by WickyNilliams** [comment]
Hmm i'm afraid i can't help you with gantry-related things - i have no idea what that is :)

But yes you will likely need vendor prefixes e.g. `-webkit-` for your styles
