### ISSUE TITLE
While scrolling up, is it possible to only show the navigation when I reach the top of the page?

### ISSUE THREAD

**Issue by gkatsanos** [WickyNilliams/headroom.js#185]
While scrolling up, is it possible to only show the navigation when I reach the top of the page?

I had a look at the options but couldn't see something relative.

**Comment by WickyNilliams** [comment]
Doesn't that defeat the purpose of this widget? Why wouldn't you just drop the JS and have a standard element at the top of your page?

**Comment by gkatsanos** [comment]
I have a header, part of it is being hidden when strolling down. What I
want is when I scroll back up, the full header is only visible when I reach
the top of the page. Did I explain it a bit better?

**Comment by WickyNilliams** [comment]
Oh right, yeah you should be able to do it with the `top` and `notTop` classes

**Comment by WickyNilliams** [comment]
Something like this should work (not tested, but hopefully you get the drift). When you have scrolled it shifts the header up 50% (use whatever is appropriate). When you're not at the, partly hide, when you're back at the top, reveal.

```css
.headroom--not-top {
  transform: translateY(-50%); /* or whatever is appropriate */
}
.headroom-top {
  transform: translateY(0);
}

**Comment by gkatsanos** [comment]
Thanks for answering. These are my options:
```javascript
        var headroom  = new Headroom(myElement, {
            "offset": 205,
            "tolerance": {
              "down": 0,
                "up": 100
            },
            "classes": {
                "initial": "animated",
                "pinned": "slideDown",
                "unpinned": "slideUp"
            }
        });

```

the slideDown and slideUp classes do CSS transition/transforms. So, as soon as I scroll up, the header is hidden..

**Comment by gkatsanos** [comment]
Indeed your code helped :) I just added the animation bits. Thanks!

**Comment by WickyNilliams** [comment]
No problems. I'd advise against keyframe animations in favour of transition if possible. They're conceptually simpler, less code and do not reset to 0% if interrupted.

**Comment by gkatsanos** [comment]
I was following the best practices on your examples suggesting animate.css library..

**Comment by WickyNilliams** [comment]
Yeah, i haven't updated the docs accordingly. Use transition if you can, keyframes if you cannot (due to complexity of animation)

**Comment by gkatsanos** [comment]
I am just moving the element up and down with translateY .. so I guess it should be possible to use transation. Checking.

**Comment by WickyNilliams** [comment]
It is definitely possible for your purposes.
