### ISSUE TITLE
Doesn't seem to work using Google Polymer 1.0. Using Jquery.

### ISSUE THREAD

**Issue by SidMehta** [WickyNilliams/headroom.js#188]

**Comment by SidMehta** [comment]
Tried to use it on a paper fab element. But it didn't work.

**Comment by WickyNilliams** [comment]
Can you give any more info? Perhaps a jsfiddle or something along those lines?

**Comment by WickyNilliams** [comment]
Closing due to lack of response. Feel free to report back if you would like to discuss further
