### ISSUE TITLE
Enhancement Feature? -- Mouse Hover near top should reveal menu

### ISSUE THREAD

**Issue by emage** [WickyNilliams/headroom.js#189]
Scrolling down hides the menu -- to see the menu you have initiate a scroll.   I think a good feature may be to show the menu again if the mouse move to the top where the menu was 

Here is a example from Digital Telepathy

http://www.dtelepathy.com/blog/interviews/experience-design

Scroll down than move your mouse back to where menu was.

**Comment by WickyNilliams** [comment]
I'm not going to include this in headroom core functionality. You should be able to combine headroom with some other third party library to achieve this effect.

**Comment by andreivictor** [comment]
This can me implemented with the following code:
```
.headroom--unpinned:after {
  content: "";
  width: 100%;
  height: 40%; // adjust height to fit your needs
  position: absolute;
  top: 100%;
  left: 0;
}

.headroom--unpinned:hover {
  transform: translateY(0);
}
```
Demo: https://codepen.io/andreivictor/full/ZwbQXK.
