### ISSUE TITLE
Feature Request : reinit or setter function

### ISSUE THREAD

**Issue by jambox** [WickyNilliams/headroom.js#190]
first of all, I love headroom...it's so useful and easy to setup.

I'm currently using it in a situation where I'm setting the `offset` value dynamically:
```
offset : (function() { return Math.floor( $(window).height() * .8); })(),
```
and I think it would be really useful to have a reinitialization function that could reset this and other values when, for instance, the device orientation changes – If someone is using a tablet in portrait mode when Headroom first initializes, that window-based value will be way too tall if they switch to portrait mode.

I looked through the source and couldn't find anything that looked like a getter/setter for that option. Please let me know if I missed something.

**Comment by gavmck** [comment]
+1 for this please, came looking in the issues to see if it was here. I think I've achieved it before with a full destroy/init, but seems less than optimal.

**Comment by WickyNilliams** [comment]
You can achieve this by changing the offset value directly. e.g.

```js
var hr = new Headroom(somElement, { offset: 100 });
hr.init();

// some time later, change the value
// this could be in response to a matchMedia listener or orientationchange event or whatever
setTimeout(function() {
  hr.offset = 200;
}, 1000);
