### ISSUE TITLE
Problems in ios 9.2 webapp mode

### ISSUE THREAD

**Issue by staabm** [WickyNilliams/headroom.js#191]
when a page declares itself as "webapp-capable"[1] and the website is opened from a bookmark from the homescreen headroom does not show up and re-appear as good as it does in the regular browsing mode.

Via JS one can detect that the browser is in "webapp-mode" using `window.navigator.standalone`.

[1,2] https://developer.apple.com/library/iad/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html#//apple_ref/doc/uid/TP40008193-SW3

**Comment by WickyNilliams** [comment]
I assume this is a remnant of when safari used to fire scroll events inconsistently. Perhaps that restriction still applies to webviews in this webapp-mode. In which case, there's nothing I can do about it, sorry. It is better that you put the detection in your code and selectively switch the functionality on/off than embed it in the headroom codebase
