### ISSUE TITLE
Starting header not at the top of the page..

### ISSUE THREAD

**Issue by ddagz** [WickyNilliams/headroom.js#192]
Hey, 

i'm trying to use this with a header that about 90px down on the page before it fixes itself to the top of the page.. I see you have offset, that is only being used for the amount of pixels until it becomes unpinned. Is there another option to set so that it doesnt trigger headroom-top until, im my case, 90px down?

**Comment by anderskristo** [comment]
Try to wrap the headroom init function in another that checks if you are down 90px.

**Comment by WickyNilliams** [comment]
`headroom--top` is switched to `headroom--not-top` when you pass the offset, and vice versa. So set your offset to 90px and use those classes to target your styles.
