### ISSUE TITLE
[Question] update offset option on viewport sizes

### ISSUE THREAD

**Issue by di5abled** [WickyNilliams/headroom.js#193]
We have the need to change the offset option value based on the current viewport width. 
Is there a way to update this "on the fly", like after a breakpoint change.

I tried it with `$('header').data('headroom').offset = $header.height();` but is this the right way, or do I have to initialize it again?

**Comment by di5abled** [comment]
It seems like it's working :)
But sould I consider using another method?

**Comment by WickyNilliams** [comment]
That should be fine. I can't imagine that would cause any problems
