### ISSUE TITLE
Microsoft Edge background fixed jumps with scrollwheel 

### ISSUE THREAD

**Issue by Clearnine** [WickyNilliams/headroom.js#194]
In Microsoft Edge (Windows 10) with headroom enabled, if there is a fixed background image, using the scroll wheel causes the background to jump.  It does not happen when using the scrollbar to scroll.

See here: http://www.laserexpressinc.com/

**Comment by WickyNilliams** [comment]
Can you provide any more info? I don't have access to a windows machine or a mouse with a scroll wheel! Perhaps a reduced test case, and a screen capture (gif or video) would be super helpful

**Comment by Clearnine** [comment]
Screen recording of the issue, hopefully this helps: https://recordings.join.me/iAfsmPIOuECsh3Il60AiBA <https://recordings.join.me/iAfsmPIOuECsh3Il60AiBA>

**Comment by geckoseo** [comment]
I can reproduce this in Edge..

I might be wrong, but I think it is to do with `requestAnimationFrame`, maybe combined with the "Debouncer".

You could try dropping in a Polyfill to see if it helps.

`/*Polyfill*/
(function() {
    var lastTime = 0;
    var vendors = ['ms', 'moz', 'webkit', 'o'];
    for(var x = 0; x < vendors.length && !window.requestAnimationFrame; ++x) {
        window.requestAnimationFrame = window[vendors[x]+'RequestAnimationFrame'];
        window.cancelAnimationFrame = window[vendors[x]+'CancelAnimationFrame']
                                   || window[vendors[x]+'CancelRequestAnimationFrame'];
    }

    if (!window.requestAnimationFrame)
        window.requestAnimationFrame = function(callback, element) {
            var currTime = new Date().getTime();
            var timeToCall = Math.max(0, 16 - (currTime - lastTime));
            var id = window.setTimeout(function() { callback(currTime + timeToCall); },
              timeToCall);
            lastTime = currTime + timeToCall;
            return id;
        };

    if (!window.cancelAnimationFrame)
        window.cancelAnimationFrame = function(id) {
            clearTimeout(id);
        };
}());`

Here is a[ link to more info about the polyfill](http://www.paulirish.com/2011/requestanimationframe-for-smart-animating/), and there is a simpler Shim too:

And there might be something useful to glean from the [MSDN](https://msdn.microsoft.com/en-gb/library/windows/apps/hh453391.aspx)

**Comment by WickyNilliams** [comment]
Excuse delay in response here. Very odd behaviour indeed. I notice that your header element isn't a direct descendent of the body - i wonder if this is somehow related? Perhaps it doesn't like transforming an element whose parent has a fixed background. Worth trying.

If not, have you tried on latest very IE? If bug is still present I would consider raising an issue with them in the relevant issue tracker, as this doesn't seem to be directly related to headroom

**Comment by Clearnine** [comment]
The way our application renders everything is in a wrapper div and it would be difficult (very) to move the header to be a direct child of body.  I did just try it on IE 11 and it works fine.  It’s only Edge with the scroll wheel thats an issue. Edge with the scroll bar is fine.  No matter how you slice it Microsoft’s browsers are a pain in the a$$.

**Comment by Clearnine** [comment]
Was reviewing my email this AM.  When you say latest IE, do you mean IE 11 or Edge.  Either way I’ve tried both up to date versions and the behavior hasn’t changed.

**Comment by WickyNilliams** [comment]
I'd raise a bug with Edge team. Very little I can do about this is user land

**Comment by binjospookie** [comment]
Set "overflow: hidden" to fixed-elements.
