### ISSUE TITLE
Request to confirm tolerance and offset (angular)

### ISSUE THREAD

**Issue by HoldenCreative** [WickyNilliams/headroom.js#197]
Hello - and thanks for such an awesome library!

I am using headroom.js for scrollable on-page content, Angular.  The problem I'm seeing is that the headroom CSS classes are not updating until a certain scrolling threshold amount is detected (approx 165px).  When my scrollable content is below this amount (roughly) then headroom never "fires".

My suspicion is that the tolerance and offset declarations herein are not actually working.  Can you confirm compatibility/syntax here with Angular 1.5x and use of the scroller identifier property?

`<div aria-labelledby="wx-primary-nav-logo" class="headroom headroom--top" headroom="" tolerance='0' offset='0' scroller=".wx-menu-content">
    <header id="wx-primary-nav-header">
        <div id="wx-primary-nav-logo" class="wx-primary-nav-logo">{{::menuTitle}}</div>
        <div id="wx-primary-nav-subtitle">{{::menuSubTitle}}</div>
    </header>
</div>`

Thanks in advance! ~ sorry I don't have a better reproduce case for you. - AJH

**Comment by WickyNilliams** [comment]
I think you need to add `data-headroom` on your outer element

**Comment by HoldenCreative** [comment]
Thanks! ~ Unfortunately no luck.  data-headroom does "work" but the issue where the css class change doesn't kick in until a scroll about about 160px or so is still in effect.

Once headroom.js starts working, the scroll/class behaviour is normal and the CSS classes update immediately on any scroll down action from top, etc.

**Comment by WickyNilliams** [comment]
Hmm... well it should be fine. Have you got a fiddle i can look at. Impossible to debug something like this blind

**Comment by HoldenCreative** [comment]
Thanks - totally understand.  I was hoping you may have seen other reports.

I'll see what I can do to reproduce using codepen.io - may need a few weeks since this is in Foundation for Apps.

**Comment by HoldenCreative** [comment]
No luck easily reproducing the issue.  FWIW, I am using a flexbox container.

Thanks for your help though.
