### ISSUE TITLE
Bower support - Release the latest changes

### ISSUE THREAD

**Issue by sebastiannm** [WickyNilliams/headroom.js#198]
Hi,
I see that there are a lot of fixes that would fix the problems I have with AngularJs. But because the source folder is not included on bower, I can't use them.

Can you please build the latest version?

**Comment by indianazhao** [comment]
+1

**Comment by shanezheng** [comment]
+1

**Comment by WickyNilliams** [comment]
Done! I have dropped the `dist` folder from the repo in favour of a UMD build available on npmcdn. See README for details :)

**Comment by sebastiannm** [comment]
Great thanks @WickyNilliams, but now on bower no source/compiled files are available?

**Comment by WickyNilliams** [comment]
@sebastiannm i think i'm going to unregister headroom from bower and instead recommend installing a file directly e.g.

```bash
bower install https://npmcdn.com/headroom.js@0.8.0
```

Do you see a problem with this approach? I do not wish to commit build artefacts to the repo anymore, and so this seems like a reasonable solution (since npmcdn pulls from npm and serves up a UMD build)

**Comment by reco** [comment]
@WickyNilliams i deleted all bower_components and did run 

`bower install --save https://npmcdn.com/headroom.js@0.8.0`

i ended up with 


`── headroom.js@0.8
   └── index.0
`

**Comment by WickyNilliams** [comment]
Hmm...

This seems to work though, right?

`bower install --save https://npmcdn.com/headroom.js@0.8.0/dist/headroom.js`

**Comment by WickyNilliams** [comment]
Though confusingly, the resulting file is named index.js:

```
.
└── bower_components
    └── headroom
        └── index.js
```

**Comment by sebastiannm** [comment]
@WickyNilliams sadly that file doesn't contain the code to run with angular

**Comment by sebastiannm** [comment]
@WickyNilliams Maybe it would be simpler if you just remove the 'src' string from the bower json in the ignore object?

**Comment by WickyNilliams** [comment]
to get the angular directive:

```
bower install --save https://npmcdn.com/headroom.js@0.8.0/dist/angular.headroom.js
```

**Comment by WickyNilliams** [comment]
I'm going to re-open this to continue bower discussion

**Comment by sebastiannm** [comment]
@WickyNilliams It feels weird to make differents bower install for the  same module. And when updating it will create a new subfolder in bower_components, which makes it more difficult for the developer.

Maybe combining all the essentials in one file (Headroom.js) and just push the unminified versions of every file?

**Comment by liquidvisual** [comment]
Please update the docs to reflect the bower URL

**Comment by djdesign** [comment]
+2 for one dist minified file. With clean bower install.

**Comment by drawcard** [comment]
Can I please put in a request for an unminified version alongside a minified one? I need an unminified version in my particular workflow, which combines multiple scripts and cranks out a minified file later on in the process.

**Comment by phifa** [comment]
no ja files in the bower repo right now...

**Comment by drawcard** [comment]
Yeah I ended up pulling version 0.7.0 for the time being to get the JS file I needed

````bash
bower install --save headroom.js#0.7.0
````

I tried grabbing the latest 0.8 version using [this command](https://github.com/WickyNilliams/headroom.js/issues/198#issuecomment-197577598) but it seems to rename the JS file and that's throwing off components in my workflow. Any help or insight would be much appreciated :smile:

**Comment by WickyNilliams** [comment]
Can you test installing like so:

```bash
bower install https://npmcdn.com/headroom.js@0.9.0/bower.zip --save
```

That should give you all the files you want

**Comment by WickyNilliams** [comment]
Oh crap, forgot to include the minified files. In any case, while I fix that, can someone test please?

**Comment by sebastiannm** [comment]
@WickyNilliams I just tested it, it looks good actually.
Is there any way to always get the latest version always instead of a fixed version?

**Comment by neilhem** [comment]
@WickyNilliams initialization with jquery throws `Uncaught TypeError: $(...).headroom is not a function`

**Comment by sebastiannm** [comment]
@WickyNilliams sorry I just read the docs, forget about my question. It actually looks, i would say it's solved

**Comment by WickyNilliams** [comment]
Just published v0.9.1 which will include minified version in bower package. Install with

```bash
bower install https://npmcdn.com/headroom.js@0.9.1/bower.zip --save
```

@sebastiannm if you drop the version number from the url, it should get the latest version. Though I assumeit will take a little while to propagate to npmcdn because of caching

@neilhem have you included the jquery plugin *as well as* the main headroom file? That error would suggest not

**Comment by neilhem** [comment]
@WickyNilliams yeah I do, I have another jquery plugins which work well, except headroom.js. Also pure js initialization of headroom.js works fine.

**Comment by WickyNilliams** [comment]
Hmm well that sounds like an unrelated issue. TBH, I would just use pure js headroom. The jQuery plugin doesn't really offer much (anything!) above that. 

If you are keen on it, create a separate issue, preferably with a reduced test case. The jQuery plugin hasn't changed significantly in a long time, so it's unusual for it to stop working suddently

**Comment by neilhem** [comment]
@WickyNilliams my bad, I was using script from production build link https://npmcdn.com/headroom.js@0.8.0/dist/headroom.min.js
