### ISSUE TITLE
Blurred when fixed

### ISSUE THREAD

**Issue by spenoir** [WickyNilliams/headroom.js#199]
Hi,

I am using headroom and the angular directive to fix a menu to the top of my page. It works well but when it is fixed it is slightly blurred for some reason. Any suggestions for a fix?

**Comment by WickyNilliams** [comment]
This sounds like an issue with your CSS. All headroom does is add/remove classes in response to scrolling, so any rendering issues are due to CSS.

Sorry I can't help you
