### ISSUE TITLE
v8.0 missing the 'dist' directory

### ISSUE THREAD

**Issue by McWhorter** [WickyNilliams/headroom.js#201]
I've just updated a project to v8.0 using Bower and the result is the **headroom.js** directory missing the **dist** directory entirely. I'm using Bower v1.7.7

**Comment by WickyNilliams** [comment]
closing as a discussion about bower is happening in #198

**Comment by WickyNilliams** [comment]
Missing out the dist directory is intentional. I'm aiming to avoid committing build artefacts as they always cause confusion in PRs. I'm hoping we can work something out using npmcdn. See discussion in the other issue

**Comment by drawcard** [comment]
I need the dist directory as part of the bower process, since I use the [Sage framework](https://roots.io/sage/) which pulls raw scripts and then compiles / minifies them in a later part of the build process. Is there any chance we can have them as an option?
