### ISSUE TITLE
can't get javascript files when using bower install

### ISSUE THREAD

**Issue by hdioui** [WickyNilliams/headroom.js#206]
when i use bower install headroom folder don't have it's javascript files

**Comment by cewen** [comment]
+1 Having the same problem

**Comment by mcblum** [comment]
+1 same problem here

**Comment by itroy** [comment]
+1 me also.. missing the dist/ folder

**Comment by chambaz** [comment]
+1 same on npm

**Comment by samburgers** [comment]
+1

**Comment by electerious** [comment]
It's because the bower file [ignores almost every file](https://github.com/WickyNilliams/headroom.js/blob/master/bower.json#L4). The `dist` folder [gets generated on build](https://github.com/WickyNilliams/headroom.js/blob/master/package.json#L12), but is [not part of the git](https://github.com/WickyNilliams/headroom.js/blob/master/.gitignore#L2) and therefore not included when installing headroom.js with bower.

**Comment by quesako** [comment]
There is src folder with all the dirt but it is  include on .gitignore. So it dont't load with bower.
Thank to remove it for use with bower.

**Comment by julianxhokaxhiu** [comment]
@WickyNilliams please fix it. I'm having this issue too :(

**Comment by Landish** [comment]
+1

**Comment by volumeis** [comment]
same

**Comment by dilvane** [comment]
+1

**Comment by WickyNilliams** [comment]
Should now be available by installing like so:

```bash
bower install https://npmcdn.com/headroom.js@0.9.1/bower.zip --save
```

I am going to unregister the package from the bower registry as it's a burden to maintain (having to commit build artefacts etc)

**Comment by electerious** [comment]
Just a small reminder for every user:

```
bower install https://npmcdn.com/headroom.js@0.9.1/bower.zip --save
```

=> Will always install version 0.9.1. User won't have the chance to see if there's an update available. It's like downloading the project and putting it in a folder. Users won't have any benefit from using a package-manager for this.

```
# From the readme
bower install https://npmcdn.com/headroom.js/bower.zip --save
```

=> Always installs the newest versions, which could easily mess-up your site as soon as a new version includes breaking changes. That's a really bad idea.

---

I get your point that having to commit build artifacts is ugly, but bower still has a lot of users and it may be worth the small effort.
