### ISSUE TITLE
babel build

### ISSUE THREAD

**Issue by nevinlaughlin** [WickyNilliams/headroom.js#208]
when using a build process with babel and gulp, I get this error, Uncaught TypeError: Cannot set property 'Headroom' of undefined;

I use the plain js way:
`// grab an element
var myElement = document.querySelector("header");
// construct an instance of Headroom, passing the element
var headroom  = new Headroom(myElement);
// initialise
headroom.init(); `

**Comment by nevinlaughlin** [comment]
it errors on this line
` root.Headroom = factory();`

**Comment by nevinlaughlin** [comment]
In the UMD wrapper, Babel replaces the "this" keyword to undefined. If you change "this" to "window" it will work. Or, run this through babel.
More info here, http://stackoverflow.com/questions/34973442/how-to-stop-babel-from-transpiling-this-to-undefined.

**Comment by WickyNilliams** [comment]
Hey @nevinlaughlin could you explain this a little more? Is it a problem with babel, and *not* headroom?

**Comment by diegosantamarta** [comment]
How did you fix this error @nevinlaughlin 
Do you know about this @WickyNilliams ?

I'm having the same error

`Uncaught TypeError: Cannot set property 'Headroom' of undefined`
