### ISSUE TITLE
Stutter in Chrome / Chromium when scrolling

### ISSUE THREAD

**Issue by inorbita** [WickyNilliams/headroom.js#209]
The Chrome browser has a nasty stutter when scrolling and headroom is triggered. I noticed this in my project but it also happens on the headroom.js and playroom websites. I've tested with Chromium 49 in Ubuntu 14.04 and Chrome in Windows 10. There's no stutter in Firefox, so might be a browser bug and not sure if anything can be done about it in the script?

**Comment by WickyNilliams** [comment]
I don't have the means to test this - no access to windows or ubuntu. Have you tried adding `will-change: transform` (assuming you're using transform to animate things)?

**Comment by WickyNilliams** [comment]
I've added `will-change: transform` to the [headroom website](http://wicky.nillia.ms/headroom.js/). Can you see the issue there?

**Comment by inorbita** [comment]
That seems to have solved it, the headroom site is stutter free. The playroom still has the stutter, but I guess you haven't changed it over there yet. Thanks for looking into this!

**Comment by WickyNilliams** [comment]
Awesome, glad to hear it was that simple! Good spot, forgot to update the playroom as well. That's fixed and pushed now. 

I was also going to add a recommendation to use `will-change` in the docs, but it seems i'd already done so last month :)

Closing this issue now, as it seems to be resolved
