### ISSUE TITLE
Bower install is broken

### ISSUE THREAD

**Issue by baffleinc** [WickyNilliams/headroom.js#212]
Hey mate,

Just tried to install via bower, and you're not allowed to include minified files in the "main" property. 

On top of that, those files don't even exist :)

Cheers

**Comment by acch** [comment]
Same here - bower install is currently broken:
```
# bower install headroom.js
bower headroom.js#*             cached https://github.com/WickyNilliams/headroom.js.git#0.9.3
bower headroom.js#*           validate 0.9.3 against https://github.com/WickyNilliams/headroom.js.git#*
bower headroom.js#^0.9.3       install headroom.js#0.9.3

headroom.js#0.9.3 bower_components/headroom.js
# ls -la bower_components/headroom.js/
total 24
drwxr-xr-x 2 achim users  140 24. Apr 17:29 .
drwxr-xr-x 3 achim users   60 24. Apr 17:29 ..
-rw-r--r-- 1 achim users  929 24. Apr 17:29 .bower.json
-rw-r--r-- 1 achim users  617 23. Apr 19:29 bower.json
-rw-r--r-- 1 achim users 1079 23. Apr 19:29 LICENSE
-rw-r--r-- 1 achim users 1135 23. Apr 19:29 package.json
-rw-r--r-- 1 achim users 6811 23. Apr 19:29 README.md
```

**Comment by olach** [comment]
The docs instructs to install via Bower this way:

    bower install https://npmcdn.com/headroom.js/bower.zip --save

But I need to specify the version, so I found out this way to specify version:

    bower install https://npmcdn.com/headroom.js@0.9.3/bower.zip --save

That works. But in bower.json the following line is added:

    "headroom.js": "https://npmcdn.com/headroom.js@0.9.3/bower.zip#^0.9.3",

If a co-worker runs `bower install` the installer gives an error. You have to remove the last part to:

    "headroom.js": "https://npmcdn.com/headroom.js@0.9.3/bower.zip",

Why make it this difficult to install headroom.js? Bower is a wonderful and a simple to use tool for front-end assets. But to install headroom.js via Bower is not as straightforward as it should be.

**Comment by WickyNilliams** [comment]
@olach you are correct, that is the recommended way to install headroom for bower. When I get a chance i will unpublish headroom from the bower registry to avoid further confusion

I tested with bower v1.7.7 and installing this way worked fine (the `#^0.9.3` part was not added to the URL in dependencies). However, when i upgraded to bower v1.7.9, that segment was added to dependencies. And then it breaks. 

I would say this is a problem *with bower itself*, since it used to work and the URL [`https://npmcdn.com/headroom.js@0.9.3/bower.zip#^0.9.3`](https://npmcdn.com/headroom.js@0.9.3/bower.zip#^0.9.3) behaves as expected if you visit in a browser.

**A note on why this approach:** Bower requires you to add build artefacts to your repository, which in my mind is not acceptable. It causes needless noise in commit logs, confuses contributors (who commit the build artefacts, not realising it should only be done when a release is cut) and creates a maintenance overhead for me. This is why I'm attempting to get it working via npmcdn.

My personal advice is to drop bower and use npm (though i realise this isn't always possible)

**Comment by WickyNilliams** [comment]
I have unregistered the bower package. Please now follow instructions in README

**Comment by olach** [comment]
@WickyNilliams  I see your point and sort of understand it. It makes it easier for you and the maintainers. But it makes it harder for the end users. But I don't want to go into a debate here about this. I'm just too thankful that people like you uses their time to create really helpful open source projects without profit.

But overall, I don't like the current trend of repos going from Bower to only npm. I guess Bower needs to modernize their tool to attract the authors to keep their repos on Bower. I understand that Bower has a few limitations.

I don't see the point in mixing build scripts and frontend assets in the node_modules folder. When we build websites, we use Bower for all frontend assets and npm for all build scripts. A clear separation. For various reasons we need full control over the frontend assets and therefore commits the frontend assets into the repo. Right now we use build scripts to minify css/js. But when HTTP/2 is going mainstream we no longer need to do the minify step, and can just serve the needed files from the bower_components folder. So a see an even greater future for Bower when HTTP/2 is fully available.

But as I said, I'm really thankful that you have created headroom.js and are giving it away for free. So I'm not arguing that you should do things my way. I can still install via Bower, even if it's not as straightforward anymore.

**Comment by WickyNilliams** [comment]
I would advise that you raise an issue with bower. I reviewed their changelog and they don't mention changing the format of dependency URLs. So I assume that this is a bug that could be fixed. Then your troubles disappear :)

I wouldn't be so fast to jump on the HTTP/2 bandwagon. You will still likely have a build/bundle step. Even if you serve each file individually, you will likely have some compilation (babel?) or minification (you wouldn't want to serve files with comments etc). This article from Khan Academy describes the problems that arose when they switched to HTTP/2: http://engineering.khanacademy.org/posts/js-packaging-http2.htm

**Comment by olach** [comment]
Thanks. Will read that article.

**Comment by WickyNilliams** [comment]
@olach Are you going to report an issue to bower?

**Comment by olach** [comment]
@WickyNilliams I can do that.

**Comment by WickyNilliams** [comment]
@olach thanks!

**Comment by baffleinc** [comment]
Sorry @WickyNilliams - I'm still unclear on what the bower limitation was that meant you couldn't just publish & install via bower -i headroom.js ?

**Comment by mleathem** [comment]
Please update the documentation: to remove bower install line...
