### ISSUE TITLE
Error with angular when trying to use with latest version(0.9.3)

### ISSUE THREAD

**Issue by ghost** [WickyNilliams/headroom.js#213]
AngularJS throws an error when latest files are included: 
Error: $injector:undef
Undefined Value
Provider 'HeadroomService' must return a value from $get factory method.

**Comment by WickyNilliams** [comment]
Could you create a fiddle (or pen or bin or whatever) to demonstrate the issue?

**Comment by moosi** [comment]
+1 

I simply added it above the tab bar: https://plnkr.co/edit/b6panE?p=info

**Comment by moosi** [comment]
Are there any updates on this issue?

**Comment by sandor11** [comment]
Have no idea if this is helpful, or not but I just hacked this up in the last 15 mins. I had problems after minification, but was getting the same error you are seeing. Don't know if this will work for you.

```
/*!
 * headroom.js v0.9.3 - Give your page some headroom. Hide your header until you need it
 * Copyright (c) 2016 Nick Williams - http://wicky.nillia.ms/headroom.js
 * License: MIT
 */

(function (angular) {

  if(!angular) {
    return;
  }
  
  function hFactory() {
    return {
        headroom: function() {return window.Headroom;}
    };
  }
  
  function headroom(HeadroomFactory) {
    return {
      scope: {
        tolerance: '=',
        offset: '=',
        classes: '=',
        scroller: '@'
      },
      link: function ($scope, $element) {
        var head = HeadroomFactory.headroom();
        var options = {};
        var opts = head.options;
        for (var prop in opts) {
          options[prop] = $scope[prop] || opts[prop];
        }
        if ($scope.scroller) {
          options.scroller = document.querySelector($scope.scroller);
        }
        var headroom = new head($element[0], options).init();
        $scope.$on('$destroy', function(){
          headroom.destroy();
        });
      }
    };
  }
  
  headroom.$inject = ['HeadroomFactory'];

  angular
    .module('headroom', [])
    .directive('headroom', headroom)
    .factory('HeadroomFactory', hFactory);
  
})(window.angular);
```

**Comment by moosi** [comment]
Any updates regarding this issue?

**Comment by jenyckee** [comment]
+1

**Comment by unkindest** [comment]
This happens because [window.Headroom](https://github.com/WickyNilliams/headroom.js/blob/v0.9.3/src/angular.headroom.js#L43) is undefined. Make sure you've loaded `headroom.js`

**Comment by rwoody** [comment]
I'm using CommonJS modules (Webpack 2) and I had this same issue. I found that the AMD style module loader was being preferred to CommonJS. Swapping the order of the CommonJS/AMD check fixed the problem for me. You can [see that fix in my fork](https://github.com/rwoody/headroom.js/commit/b886fcea9a5967775e6ec1d6f5637d8575366fb0#diff-a456957200145b3b4e2f9148561c50b3).

**Comment by mcblum** [comment]
@rwoody any idea how this would look in Webpack 1? I seem to be having the same issue but cannot figure it out!

**Comment by mcblum** [comment]
update: fixed it for anyone who may need this code:

```
 // expose Headroom
 new webpack.ProvidePlugin({
    'window.Headroom': 'headroom.js/dist/headroom.js'
})
```

**Comment by WickyNilliams** [comment]
Closing in favour of #333, which will look at all angular issues
