### ISSUE TITLE
 ENOTFOUND Package headroom.js not found

### ISSUE THREAD

**Issue by paul-barry-kenzan** [WickyNilliams/headroom.js#214]
When attempting to install via `bower install headroom.js` I get the follow error: 

** ENOTFOUND Package headroom.js not found**

This has caused my CI deployments to fail. I was forced to fork your repo to be able to include in my project. Has anything been changed that would lead to this repo not being accessible via bower? (npm installs properly)

**Comment by WickyNilliams** [comment]
Yes, I unpublished. Headroom should be installed via npmcdn (see instructions in README)

**Comment by obuckley-kenzan** [comment]
Thanks @WickyNilliams

**Comment by WickyNilliams** [comment]
Not sure if sarcastic thanks, but i'll accept it anyway :P

Be aware, there seems to be a problem with latest bower, where it won't install correctly if you do it via the command line. Instead manually add to your dependencies field

**Comment by obuckley-kenzan** [comment]
@WickyNilliams 
Definitely not intended, I meant as in a fast reply.  Working on a release this morning.  :)

Was able to fork and install that way, so all good!

**Comment by WickyNilliams** [comment]
Haha OK :)

I know i'm causing a lot of upheaval by removing from bower registry, but it makes maintenance and contributing much easier. And I value that a lot

**Comment by obuckley-kenzan** [comment]
@WickyNilliams 
Totally understand.  I am making the move to JSPM instead of Bower myself.

Have a good one and thanks for your work on this project!

**Comment by obuckley-kenzan** [comment]
FYI, this works for us, if it helps anyone else
```javascript
$ bower install git@github.com:WickyNilliams/headroom.js.git --save
bower headroom.js#*             cached git@github.com:WickyNilliams/headroom.js.git#0.9.3
bower headroom.js#*           validate 0.9.3 against git@github.com:WickyNilliams/headroom.js.git#*
bower headroom.js#^0.9.3       install headroom.js#0.9.3
bower                          no-json No bower.json file to save to, use bower init to create one

headroom.js#0.9.3 bower_components/headroom.js
```

**Comment by WickyNilliams** [comment]
@obuckley-kenzan There are no built files in the repo. So whilst the install might complete, you will not get anything usable. Instead install from npmcdn like:

```bash
bower install https://npmcdn.com/headroom.js@0.9.3/bower.zip -- save
```

**Comment by obuckley-kenzan** [comment]
Thanks @WickyNilliams , but we are using 0.7.0 and that was not available on the CDN.
```
$ bower install https://npmcdn.com/headroom.js@0.7.0/bower.zip --save
bower bower#*               not-cached https://npmcdn.com/headroom.js@0.7.0/bower.zip#*
bower bower#*                  resolve https://npmcdn.com/headroom.js@0.7.0/bower.zip#*
bower bower#*                 download https://npmcdn.com/headroom.js@0.7.0/bower.zip
bower bower#*                    EHTTP Status code of 404
```

**Comment by WickyNilliams** [comment]
Bummer! 

There have been no breaking changes, you should be good to upgrade to latest :)

**Comment by obuckley-kenzan** [comment]
good to know!   thanks.

btw, bower install from github does pull down dist files and also works with `wiredeps`

**Comment by WickyNilliams** [comment]
I guess that is from an old version. I just did a fresh install:

```bash
$ bower install https://github.com/WickyNilliams/headroom.js.git --save

bower headroom.js#*             cached https://github.com/WickyNilliams/headroom.js.git#0.9.3
bower headroom.js#*           validate 0.9.3 against https://github.com/WickyNilliams/headroom.js.git#*

$ tree
.
├── bower.json
└── bower_components
    └── headroom.js
        ├── LICENSE
        ├── README.md
        ├── bower.json
        └── package.json

2 directories, 5 files
```

**Comment by OlegFilth** [comment]
when requires with browserify I have error like this `bundle.js?ver=1.0.0:1 Uncaught TypeError: Cannot read property 'unslick' of undefined
    at m.fn.init.t.fn.slick (bundle.js?ver=1.0.0:1)`
