### ISSUE TITLE
bower registry lost headroom.js?

### ISSUE THREAD

**Issue by btmurrell** [WickyNilliams/headroom.js#218]
wtf?

$ bower info headroom.js
bower                        ENOTFOUND Package headroom.js not found

**Comment by WickyNilliams** [comment]
Please see README for updated instructions on installing headroom via bower

**Comment by btmurrell** [comment]
I saw the one liner to bower install from npmcdn in the readme, but we've been getting it from bower registry forever.  will it no longer be available in bower registry from this point forward?  if so, it would be good to state this explicitly since it is a significant change that will break builds. 

thanks!
