### ISSUE TITLE
Main files missing

### ISSUE THREAD

**Issue by nouveller** [WickyNilliams/headroom.js#220]
This is kind of related to #219 in this respect,

> adds a folder from a strange location without any *.js files in it.

The main files specified in `bower.json` seem to be missing from the repo, these in question.

```json
{
  "main": [
    "dist/headroom.js",
    "dist/headroom.min.js",
    "dist/jQuery.headroom.js",
    "dist/jQuery.headroom.min.js",
    "dist/angular.headroom.js",
    "dist/angular.headroom.min.js"
  ]
}
```

In turn, when installing with Bower and using https://github.com/ck86/main-bower-files, nothing gets loaded in as the main files are missing.

Ideally, just `dist/headroom.js` would be the "main file" specified in `bower.json` and all the above files committed into the package. Then if someone requires the more specific jQuery or Angular version, they use main-bower-files' override options.

Work around for now is to install the main file directory e.g.

```
bower install --save https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.3/headroom.js
```

**Comment by WickyNilliams** [comment]
Look in the README (https://github.com/WickyNilliams/headroom.js#install-with-bower), you will see instructions on how to install with bower. I no longer use the bower registry for delivering headroom, but npmcdn instead

**Comment by nouveller** [comment]
Sorry, I didn't see the `README` as I was fixing the issue for a colleague.

Perhaps remove the main files from the `bower.json` altogether, it'd remove some confusion for people that search for it on Bower.

I get why you'd try to avoid this from https://github.com/WickyNilliams/headroom.js/issues/219#issuecomment-218782430. 

It's quite often someone may do `bower search headroom`, install `headroom.js` and then wonder why it's not working.

Just a thought 😸

**Comment by WickyNilliams** [comment]
Yes, sorry to be curt, I was in the middle of something myself.

Unfortunately the main files have to stay in the bower.json as that is what npmcdn uses to generate the bower.zip.

I'm surprised it turns up in the bower search since i unregistered the package!

**Comment by nouveller** [comment]
Oh, interesting. I didn't know npmcdn, it makes total sense.

👍
