### ISSUE TITLE
bower support - broken?

### ISSUE THREAD

**Issue by JohannesFerner** [WickyNilliams/headroom.js#221]
Hi,

the Bower .zip download integration seems to be broken: 

```
$ bower install https://npmcdn.com/headroom.js/bower.zip --save (readme)
```
(this works fine, correct download & extraction)

results in the following bower.json content:
```
...
"headroom.js": "https://npmcdn.com/headroom.js/bower.zip#^0.9.3"
...
```

clearing the bower-assets and installing all my assets via `bower install` results in: 

```
$ bower install
bower headroom.js#^0.9.3  ENORESTARGET URL sources can't resolve targets
```

So we will run into problems when we want to install, build this on a CI. 

Is there a way to use headroom.js' bower support with sem-ver?

**Comment by JohannesFerner** [comment]
bower install https://npmcdn.com/headroom.js/bower.zip --save

**Comment by JohannesFerner** [comment]
updated issue

**Comment by WickyNilliams** [comment]
I would say this is an issue with bower. That URL is valid, and npmcdn handles it perfectly fine. Perhaps raise an issue with bower?

One workaround for now is to manually add the URL to your bower.json, removing the hash fragment. If you want to lock the version, you can include the version number in the URL for npmcdn e.g.

```js
"dependencies": {
  "headroom.js": "https://npmcdn.com/headroom.js@0.9.3/bower.zip"
}
```
