### ISSUE TITLE
difficult to use

### ISSUE THREAD

**Issue by AmirFawzy** [WickyNilliams/headroom.js#222]
it's a pretty cool effect navbar but after reading all documentation of the plugin and trying so many times to use it with jQuery but that dosen't work i did exactly what you say in doc step by step ... i don't know if i did something wrong or not but the thing i am sure about it is many people that plugin dosen't work with them ...
may with video explain how to use this plugin with jQuery and js it's the best way to figure out how headroom.js work

thank u and hopefully that plugin becomes easy to use soon.

**Comment by WickyNilliams** [comment]
I'm not sure what I can do here. I'm not producing a video, I don't have time. The documentation is pretty clear. The website itself even has a working example. I'm afraid I can't help more than that
