### ISSUE TITLE
scrolling with arrow keys

### ISSUE THREAD

**Issue by okamotok** [WickyNilliams/headroom.js#223]
It would be nice if this would work when using arrow keys to scroll.  When I am in the middle of a page and hit the page up key the header shows.  But when I  use the up arrow key the header does not show.   I'm using Chrome 50.0.2661.102 (64-bit) on Mac OS X 10.9.5.

**Comment by WickyNilliams** [comment]
Works for me on Chrome on OSX. I just tested on the [headroom website](wicky.nillia.ms/headroom.js/) and it behaves as expected.
