### ISSUE TITLE
Disable classes

### ISSUE THREAD

**Issue by fabsn182** [WickyNilliams/headroom.js#226]
Any chances to remove classes that are not required? When settings `notBottom: false`, the class shouldn't be set to the default one. Imho in this case there would also be no need to call the specific function.

**Comment by WickyNilliams** [comment]
Can I ask why? If you don't write CSS for them, it makes no difference whether they're present or not. If you write CSS for them you're going to be using them.

**Comment by fabsn182** [comment]
I personally just don't like adding classes to an element if they're unnecessary, tracking things that don't need to be tracked/calculated.

**Comment by WickyNilliams** [comment]
If there were specific performance problems related to this I would reconsider my position. But as it stands, there are none, so i will leave it as is
