### ISSUE TITLE
jQuery plugin not working ?

### ISSUE THREAD

**Issue by joomlolo** [WickyNilliams/headroom.js#227]
Hello WickyNilliams,
Thanks for your script.
I notice that with plain js, no problem,but when I try to use the jQuery plugin,no class is added.
I don't see any change in the html.no effect.

With plain js I see the classes that are added but nothing with jquery and no error in firebug.

there is a fiddle here,I try to target an "id" in this example: $("#header").headroom();
http://jsfiddle.net/7ku7f13k/1/

maybe I do something wrong
If you have time to take a look,please
sorry for my English

Regards,
Laurent

**Comment by joomlolo** [comment]
Yet, even with plain.js,I can't, strange,could you post a jsfiddle ?

**Comment by WickyNilliams** [comment]
Please read the documentation more thoroughly.

Firstly, all headroom does is add/remove classes. You have to bring your own CSS.

Secondly, you were adding the scripts directly from githubusercontent.com which doesn't not serve JS with the correct mime type. This is blocked by modern browsers.

I have updated your fiddle to demonstrate these changes. It now works http://jsfiddle.net/7ku7f13k/3/

**Comment by joomlolo** [comment]
the fiddle was just here for example sorry(I know for the css), I do on my local computer for the moment,sorry I didn't know for the mime type.
For my problem it was because I copy /paste:headroom.js from here=>
https://raw.githubusercontent.com/WickyNilliams/headroom.js/master/src/Headroom.js
now I take here https://npmcdn.com/headroom.js@0.9.3/dist/headroom.js
and it is ok

Thanks a lot for your work and your quick answer
everything is ok now,thank you!

Regards
