### ISSUE TITLE
Error in bower install

### ISSUE THREAD

**Issue by slacto** [WickyNilliams/headroom.js#228]
I get the same error on both
bower install https://npmcdn.com/headroom.js/bower.zip --save
bower install headroom.js --save

The two errors are:
bower bower#*             invalid-meta The "main" field cannot contain minified files
bower bower#*             invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["dist/headroom.js","dist/headroom.min.js","dist/jQuery.headroom.js","dist/jQuery.headroom.min.js","dist/angular.headroom.js","dist/angular.headroom.min.js"]

**Comment by WickyNilliams** [comment]
It should still work fine. 

![screen shot 2016-06-02 at 14 36 27](https://cloud.githubusercontent.com/assets/1091390/15774647/56f7f008-2975-11e6-956d-6c9f870094e9.png)

Everything is installed as expected

**Comment by slacto** [comment]
Not here. I only get .json files LICENCE and README.md. No folders or js files at all

**Comment by WickyNilliams** [comment]
Make sure you install from npmcdn, not bower registry.

**Comment by slacto** [comment]
Thanks, no errors now
