### ISSUE TITLE
Wordpress....

### ISSUE THREAD

**Issue by creator2earth** [WickyNilliams/headroom.js#229]
Hey so right now Im working on this Wordpress Theme and I have everything hooked up the right way but the issue I'm having is that only the elements inside of my header are hiding and unhiding themselves? Like the a link and everything else in my nav seem to be functioning as it should but the actual header isn't going anywhere. Do I set my header to a fixed position? or is it just Wordpress messing everything up per usual? I can  provide code if need be. Thanks :-)

**Comment by WickyNilliams** [comment]
Yes you need `position: fixed` on your header element. If that doesn't work, please supply a fiddle. Closing for now.

**Comment by creator2earth** [comment]
Hey thanks for getting back to me....and closing this. plugin works great! And ya the header position fixed worked great with the custom css I pulled from a previous issue. Thanks again! :-)
