### ISSUE TITLE
bower.json fails ENORESTARGET URL sources can't resolve targets

### ISSUE THREAD

**Issue by slacto** [WickyNilliams/headroom.js#230]
I have the same issue as here: https://github.com/bower/bower/issues/2272

When I run:
call bower install https://npmcdn.com/headroom.js/bower.zip --save
It add this to my bower.json:
"headroom.js": "https://npmcdn.com/headroom.js/bower.zip#^0.9.3"

That makes my web.build fail:
[Exec] bower headroom.js#^0.9.3              ENORESTARGET URL sources can't resolve targets

If I remove #^0.9.3 it builds:
"headroom.js": "https://npmcdn.com/headroom.js/bower.zip"

**Comment by WickyNilliams** [comment]
I am certain this is a bug with bower. There is absolutely nothing wrong with that URL, npmcdn responds to the url fine, but bower adds the problematic hash fragment, and then chokes on it.

If you manually add the URL (with the version number) to your bower.json, everything should work fine

**Comment by WickyNilliams** [comment]
I am closing this, as I have commented on the bower issue. Hopefully they will fix this

**Comment by renkosteenbeek** [comment]
I just bumped into the same problem. Quite annoying =(

**Comment by jaworskm** [comment]
This is still a problem. Is there a solution yet?
