### ISSUE TITLE
v0.9.3 is incompatible with angular

### ISSUE THREAD

**Issue by thatisuday** [WickyNilliams/headroom.js#232]
![image](https://cloud.githubusercontent.com/assets/5711821/15999885/34843a1a-3166-11e6-9e05-0d9a88e49dd5.png)

![image](https://cloud.githubusercontent.com/assets/5711821/15999890/4864bb18-3166-11e6-9ed8-cb849701bf18.png)

I am receiving above error for angular 1.5.6.

**Comment by WickyNilliams** [comment]
I'm closing this in the interest of cleaning up the issue tracker. If you still have issues, please comment here
