### ISSUE TITLE
Current bower package has no js code

### ISSUE THREAD

**Issue by smlombardi** [WickyNilliams/headroom.js#234]
After updating to the latest in my bower.json and installing, I got 404 errors looking for the headroom js files.

I checked the headroom folder in bower_components, and sure enough there is no `src` folder in there, **nor any javascript files at all**.  I needed to roll back to the older version I had in my repo.

**Comment by WickyNilliams** [comment]
See the README for latest installation instructions. See various issues if you wish to see the reasoning behind the change

**Comment by smlombardi** [comment]
Do you mean `bower install https://npmcdn.com/headroom.js/bower.zip --save`?

Because that didn't work either.

**Comment by yuvilio** [comment]
@smlombardi , i've found that i needed to delete the resulting bower directory (e.g.: `bower_components/headroom.js/`) and then running the bower install command you noted (the readme one) works and you get the .js files (like `dist/headroom.js`) there.
