### ISSUE TITLE
Angular JS does not add classes to header on scroll

### ISSUE THREAD

**Issue by m-kermani** [WickyNilliams/headroom.js#237]
I am almost sure the problem is from me! But I need to ask because I need to use Headroom

In Angular my header is a partial and I include it to my home using ng-include and I added the **headroom** directive to my header, I also added headroom.js and angular.headroom.js to my page but still when I scroll down and I watch my console, nothing adds to the header. I don't know why headroom does not add classes to the header by scroll down or even scroll up.

I tested headroom with Angular in other pages, it is working! I don't know if is there any problem with Angular 1.5 version or maybe with my page codes!

Now, I changed the headroom.js with other course (https://npmcdn.com/headroom.js@0.9.3/dist/headroom.min.js) and now it returns and error and says:

> TypeError: Cannot read property 'classList' of null

If you know what the problem is, let me know
Thanks

**Comment by AdamDiment** [comment]
This is happening to me as well, I'm using angular 1.5 - is this the problem?

**Comment by JoshuaNovak919** [comment]
I am also having this issue. Any ideas?
