### ISSUE TITLE
empty classes not supported

### ISSUE THREAD

**Issue by adick** [WickyNilliams/headroom.js#238]
It would be nice if empty classes were supported.
For example, I only need a class when the element is pinned:

```
classes: {          
    initial: '',            
    pinned: 'is-sticky',            
    unpinned: ''        
    // ...
}
```

currently, the default classes are applied when empty classes are set.

**Comment by MattGreyDesign** [comment]
I have no need for the bottom/notBottom options, so I'd quite like to be able to do this as well.
something like above or `notBottom: null` would be ideal.

**Comment by WickyNilliams** [comment]
I don't see the point in making this change. If you don't want to use the classes, just don't write any css for them

**Comment by hacknug** [comment]
Would you consider reopening this issue? As I see it, by not allowing users to do this, headroom is adding/removing unneeded classes all the time thus impacting performance (even if negligible for most devices).

I'd be willing to make a PR for this if you'd consider making this an option.
