### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by kodeine** [WickyNilliams/headroom.js#239]
As the title says, does it support ng2? Or any plans for it?

**Comment by WickyNilliams** [comment]
If I'm honest: I haven't the slightest clue :) I don't use angular, and the directive was contributed by someone else.

Do you have any idea?

**Comment by mhverbakel** [comment]
No, it does not support Angular (the official name of Angular v2.x.x and above). This library was built for AngularJS (which is essentially Angular v1.x.x), and those are not compatible with the rework of Angular.

I think this library (or a different project) should expose a NgModule to be used in Angular.

**Comment by WickyNilliams** [comment]
Closing in favour of #333, which will look at all angular issues
