### ISSUE TITLE
Bower install does not work

### ISSUE THREAD

**Issue by dlewand691** [WickyNilliams/headroom.js#240]
Bower doesn't install all files, only bower.json, package.json, README.md and license.

**Comment by thatisuday** [comment]
@dlewand691 

{
"headroom.js": "https://npmcdn.com/headroom.js/bower.zip"
}

Add this to your bower dependencies

**Comment by dlewand691** [comment]
Still does not work. Bower says package not found. Cannot get it to work with any way I've tried.

**Comment by goneale** [comment]
Yes, still has errors
`bower bower#*               not-cached https://npmcdn.com/headroom.js/bower.zip#*
bower bower#*                  resolve https://npmcdn.com/headroom.js/bower.zip#*
bower headroom.js#*             cached https://unpkg.com/headroom.js/bower.zip
bower headroom.js#*           validate https://unpkg.com/headroom.js/bower.zip#*
bower bower#*                 download https://npmcdn.com/headroom.js/bower.zip
bower bower#*                  extract bower.zip
bower bower#*             invalid-meta The "main" field cannot contain minified files
bower bower#*             invalid-meta The "main" field cannot contain minified files
bower bower#*             invalid-meta The "main" field cannot contain minified files
bower bower#*             invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["dist/headroom.js","dist/headroom.min.js","dist/jQuery.headroom.js","dist/jQuery.headroom.min.js","dist/angular.headroom.js","dist/angular.headroom.min.js"]
bower headroom.js#*           resolved https://npmcdn.com/headroom.js/bower.zip
bower headroom.js#*            install headroom.js`

**Comment by pmd-bgermain** [comment]
The dist folder is not pushed to the repository and the src folder is ignored so when you install via bower you only get the files that are not in ignored list in bower.json
You should choose a way to expose your dist files or src files to your end user.

**Comment by jcelletti** [comment]
please fisx this issue. it should only take a few minutes to do so that people can stay on specific versions

**Comment by WS-Theme** [comment]
Thanks for your Message.

From 24.12.2016 - 08.01.2017 our Office is closed cause of Holidays. Maybe we will answer in this time but it could take some time. Please note that we also doesn't provide support for our Templates or Extensions in this Time Period.

Thank you.

**Comment by jdbaker** [comment]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External>bower install "
headroom.js": "https://npmcdn.com/headroom.js/bower.zip"
bower not-cached    https://npmcdn.com/headroom.js/bower.zip#*
bower resolve       https://npmcdn.com/headroom.js/bower.zip#*
bower download      https://npmcdn.com/headroom.js/bower.zip
bower extract       bower#* bower.zip
bower invalid-meta  for:C:\Users\XXX\AppData\Local\Temp\XXX\bowe
r\c3a4419258c98e9dc1dd5c36a7ec9fad-15308-PxA2ts\bower.json
bower invalid-meta  The "main" field cannot contain minified files
bower invalid-meta  The "main" field cannot contain minified files
bower invalid-meta  The "main" field cannot contain minified files
bower invalid-meta  The "main" field has to contain only 1 file per filetype; fo
und multiple .js files: ["dist/headroom.js","dist/headroom.min.js","dist/jQuery.
headroom.js","dist/jQuery.headroom.min.js","dist/angular.headroom.js","dist/angu
lar.headroom.min.js"]
bower resolved      https://npmcdn.com/headroom.js/bower.zip#e-tag:W/"21e9-15
bower ENOTFOUND     Package headroom.js: not found

**Comment by WickyNilliams** [comment]
TBH i'm considering dropping bower support. I don't use it, I constantly break it, and perhaps most importantly - npm has won

**Comment by 1ambda** [comment]
Can't download 0.9.3 from unpkg.com. 

- https://unpkg.com/headroom.js@0.9.3/bower.zip

![image](https://cloud.githubusercontent.com/assets/4968473/25311085/f00e05aa-2831-11e7-9fe4-7307245cea18.png)

**Comment by valeriosillari** [comment]
today it seems bower install does  not work again. anyone same issue?

**Comment by tmoffett-centrify** [comment]
Same issue here!

**Comment by webrgp** [comment]
Same issue :-(

**Comment by WickyNilliams** [comment]
I'm going to drop bower support since it has been deprecated / put into maintenance mode. You should be able to continue using it, by following the [advice here](https://github.com/WickyNilliams/headroom.js/issues/268#issuecomment-302870293).
