### ISSUE TITLE
jQuerty 1.7.2. 'destroy' of undefined

### ISSUE THREAD

**Issue by lexuspro** [WickyNilliams/headroom.js#242]
Hello, friends! Tell me please, I use the website on the library jQuerty 1.7.2.
I have tried to install headroom two methods, including 
`<header data-headroom data-tolerance="5" data-offset="55" data-classes='{"initial":"animated","pinned":"slideDown","unpinned":"slideUp","top":"headroom--top","notTop":"headroom--not-top","bottom":"headroom--bottom","notBottom":"headroom--not-bottom"}' class="site-header header_area">
`
then I added a custom.js
`(function ($) {
    "use strict";
    $(document).ready(function(){
$("header").data("headroom").destroy();
}(jQuery));
`
``
but unfortunately, the browser console says **Uncaught TypeError: Cannot read property 'destroy' of undefined**
Can you please tell me how to fix this? I have little experience with installing scripts.
I should add that I connected from 2 files:
Headroom.js and jQuery.headroom.js

**Comment by erwstout** [comment]
The first thing that sticks out to me is if you're trying to install/use Headroom then why are you calling the destroy method in your `custom.js` file?

Secondly, check to make sure that you are calling the headroom js files after your jQuery install.

Third - you don't specify that you're using Angular, so if you're not using Angular make sure you go back and look at the documentation on the proper way to install for your site/application.

Hope that helps or pushes you in the right direction.

**Comment by WickyNilliams** [comment]
I believe the solution is: `$("header").headroom("destroy")`
