### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by caseydev** [WickyNilliams/headroom.js#249]
I have called the headroom.js and jquery.headroom js manually as well initial $("#main-header").headroom(); also. But problem appears like 
![image](https://cloud.githubusercontent.com/assets/4696688/18774362/f61f555e-8177-11e6-8106-39169e4a7834.png)
What else missing please can you help me?

**Comment by WickyNilliams** [comment]
a stack trace would help... 

questions like these are best asked on stackoverflow, where there many people willing to help
