### ISSUE TITLE
Just to be honest :)

### ISSUE THREAD

**Issue by artf** [WickyNilliams/headroom.js#252]
![schermata 2016-10-19 alle 21 23 16](https://cloud.githubusercontent.com/assets/11614725/19533939/191419da-9642-11e6-893f-52a2d6216a09.png)

**Comment by lukasoppermann** [comment]
Gzip?

**Comment by artf** [comment]
There is no label about gzip so I simply expect what I see, no?

**Comment by lukasoppermann** [comment]
I don't know, normally though all js package sizes are calculates using gzip. So I would guess this is what the page is referring to.

**Comment by artf** [comment]
Generally I see an indication about gzipped size :/

**Comment by WickyNilliams** [comment]
Haha, fair. I think it was min/gzip size. Will either update or add a note
