### ISSUE TITLE
Angular 1.5.8 + Headroom 0.9.3 Setup issue

### ISSUE THREAD

**Issue by atsoy** [WickyNilliams/headroom.js#254]
Hi folks,

have not found similar issues here, so here is mine:

It's actually strange, cause I installed it via npm, got all necessary files, also put it into my `index.html` like:

```
<script src="path/to/angular.headroom.min.js"></script>
<script src="path/to/headroom.min.js"></script>
```

Made also part with: 
```
angular.module('app, [
  ...
  'headroom',
  ...]
```

but still get the error message, cannot find headroom module.

```
angular.js:13920 Error: [$injector:modulerr] Failed to instantiate module book-insights due to:
Error: [$injector:modulerr] Failed to instantiate module headroom due to:
Error: [$injector:nomod] Module 'headroom' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument
```

Does someone have similar issue?

Ty in advance!

**Comment by devdesign12345** [comment]
Include "headroom.min.js" first then  ''angular.headroom.min.js" like this.

<script src="path/to/headroom.min.js"></script>
<script src="path/to/angular.headroom.min.js"></script>

**Comment by atsoy** [comment]
I solved it by:
```
require('headroom.js/dist/headroom.js');
require('headroom.js/dist/angular.headroom.js');
```

in my index.js. 

To use it with angular I don't need to add it as
`<script src="path_to_headtoom"></script>`in my index.html
