### ISSUE TITLE
Headroom is not defined

### ISSUE THREAD

**Issue by jennykortina** [WickyNilliams/headroom.js#256]
Having the same issue as: Headroom is not defined #53

I'm trying to use headroom on a Wordpress site, both the JS files are being loaded, but the functions don't work when they call them (in the page or console).

I'm trying to use the straight up JS version on the page, and am logging 'myElement'  Any thoughts on why the functions don't work?

**Comment by OndrejVertat** [comment]
Same issue here. Tried bower/npm/straight js download from the web. All with no luck.

**Comment by Pyth0ff** [comment]
Which syntax do you use? Plain JS or jQuery?

I had a similar problem some weeks ago by using `headroom.js` with jQuery. It took me some time, but I could solve it. The problem was that the needed jQuery plugin file was missing, where the necessary function was defined.

**Comment by jennykortina** [comment]
@Pyth0ff I tried both the straight up js and then the jquery being sure to include the extra file and neither worked.  Thank you though!

**Comment by wasabigeek** [comment]
Any chance is it because `headroom.js` is being loaded after your function to call it?

**Comment by WickyNilliams** [comment]
Assume this has since been solved. Closing in the interest of cleaning up the issue tracker. Please comment if you are still having issues
