### ISSUE TITLE
responsive offset

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [WickyNilliams/headroom.js#257]
hey there,
thanks for this cool plugin.
I have an issue with responsive offset. can't update the offset on window resize.

I stored the offset value, that is height of an element, in a variable. and update that variable on window resize.
but the offset is what is set in the initial. and it won't change on window resize.

is there anything that I can do for this?

thanks

**Comment by WickyNilliams** [comment]
you should be able to simply set the offset property of your headroom instance:

```js
var hr = new Headroom(element);
hr.init();

window.addEventListener("resize", function(e) {
  hr.offset = getOffsetValue();
}, false);
```

**Comment by mikemedoro** [comment]
I'm having trouble getting this to work. It seems to be returning the correct value on window resize but it's not getting applied to the headroom offset.

```
function getOffset() {
    let pageHeader = $('.post-header').outerHeight();
    return pageHeader;
}
const options = {
    offset: getOffset(),
}
const header = document.querySelector('.site-header');
const headroom = new Headroom(header, options);
headroom.init();

window.addEventListener('resize', function (e) {
    headroom.offset = getOffset();
    console.log(headroom.offset);
}, false);
```

**Comment by ABaier** [comment]
Same problem here. Did anybody achieve this in the end? Thanks for your help!
