### ISSUE TITLE
how it work

### ISSUE THREAD

**Issue by AmirFawzy** [WickyNilliams/headroom.js#258]
hello,
this plugin drive me to crazy it's not work with me at all i did tried everything i tried with jquery, js and by changing markup but it doesn't work and documentation not explain how markup should to be and what about css that also inexplicit...

**Comment by AmirFawzy** [comment]
okay after trying again i figure out something i think there's a problem with headroom.js file cuz of when i take the main.js file from demo example and replace it with headroom.js the problem is solved and working good..

**Comment by WickyNilliams** [comment]
You're supposed to load the files in the following order:

1. headroom.js
2. jquery.headroom.js
