### ISSUE TITLE
How to slide out, if below offset?

### ISSUE THREAD

**Issue by Pyth0ff** [WickyNilliams/headroom.js#259]
I've been trying quite a while to figure out how to slide out my navigation nicely, if I'm below my offset. If the header is visible the navigation should be positioned relative to its parent.

Can anybody give me a suggestion how could I achieve this goal? Can I translate somehow from my offset position to the top of the page?

```scss
.headroom {
    position: relative;

    will-change: transform;
    transition: transform 200ms ease-in-out;

    &--top {
    }

    &--not-top {
    }

    &--pinned {
        position: fixed;
        transform: translateY(0%);      
    }

    &--unpinned {
        position: fixed;
        transform: translateY(-100%);
    }
}

**Comment by WickyNilliams** [comment]
Not sure what you're trying to do here. Closing in the interest of cleaning up issues. Please comment here if you're having issues still
