### ISSUE TITLE
Is unkn0wn-kgb/headroom.js the official bower registry of this library?

### ISSUE THREAD

**Issue by jimmyko** [WickyNilliams/headroom.js#260]
I tried to use bower to install headroom.js and accidentally installed unkn0wn-kgb/headroom.js. I would like to know if it is the way to install it? I know README.md has stated the way to install, but is there any reason not register on bower? Thanks.

**Comment by jonmunson** [comment]
The official bower registry is "headroom-js", but this will only bring the source in via Bower. To install with Bower, run `bower install https://unpkg.com/headroom.js/bower.zip --save` as instructed on the Readme.

**Comment by jimmyko** [comment]
Thanks!
