### ISSUE TITLE
headroom.js can't be used in angular

### ISSUE THREAD

**Issue by sofichael** [WickyNilliams/headroom.js#263]
In angular.headroom.js  at last line the 'window.Headroom' is undefined

**Comment by rwoody** [comment]
Are you using CommonJS or AMD modules? Check out [my comment](https://github.com/WickyNilliams/headroom.js/issues/213#issuecomment-281106943) on #213

**Comment by WickyNilliams** [comment]
@sofichael please do not create duplicate issues. If you have any further comments, please add them to #264
