### ISSUE TITLE
angualr issue

### ISSUE THREAD

**Issue by sofichael** [WickyNilliams/headroom.js#264]
In angular.headroom.js  at last line the 'window.Headroom' is undefined

**Comment by atsoy** [comment]
hi, make sure you have loaded `headroom.js`.

Mentioned [here](https://github.com/WickyNilliams/headroom.js/issues/213#issuecomment-234040924)

**Comment by rwoody** [comment]
Are you using CommonJS or AMD modules? Check out [my comment](https://github.com/WickyNilliams/headroom.js/issues/213#issuecomment-281106943) on #213

**Comment by WickyNilliams** [comment]
In the interest of burning through issues, I'm closing this since @sofichael has not replied. If you would like to continue discussion, please comment here
