### ISSUE TITLE
Question about ReactJS suport 

### ISSUE THREAD

**Issue by CusProjects** [WickyNilliams/headroom.js#266]
i tired to do this 

`
let myElement = document.getElementById("myTopnav");
let headroom  = new Headroom(myElement);
headroom.init();
`
`<ul className="headroom topnav" id="myTopnav">
						  <li><a href="#home">GO-EAT</a></li>
						  <li><a href="#news">News</a></li>
						  <li><a href="#contact">Contact</a></li>
						  <li><a href="#about">About</a></li>
						  <li className="icon">
						    <a onClick={this.onClickNavButton}>&#9776;</a>
						  </li>
						</ul>	`

**Comment by RusinovAnton** [comment]
Hi, could you please try to describe your problem better?

**Comment by WickyNilliams** [comment]
Will need more of an explanation if this issue is to be solved. If you want something that works out of the box in react, i can recommend `react-headroom`
