### ISSUE TITLE
Absolute top

### ISSUE THREAD

**Issue by samburgers** [WickyNilliams/headroom.js#267]
Hi, 

I need to add one header behaviour for the `offset-top` and a separate behaviour to the absolute-top of the page scroll, even when an offset is declared. Is this currently possible?

Many thanks!

**Comment by WickyNilliams** [comment]
No, this is not currently possible. What's your use case?

**Comment by WickyNilliams** [comment]
Closing as I doubt I will add this feature. But I'm happy to discuss further
