### ISSUE TITLE
Initial state with static (not fixed) header

### ISSUE THREAD

**Issue by dangelion** [WickyNilliams/headroom.js#273]
Hi, I'll begin saying I'm loving hard this plugin! Really.

I need to do an header like this:
https://www.chandeliercreative.com/
The header is static from start and becomes pinned after an offset (when scrolling down) and then back to static (when it's back to the top).

I'm trying to do that, check here:
http://codepen.io/netgloo/pen/KmGpBL

but I have 2 problems:
1) scrolling down from top: when the header becomes pinned, I see it slides down and suddenly slides up
2) scrolling up from middle page: when the header arrives to the offset it disappears, but I need keeping it pinned to the top

Is it possibile to do that? Could you help me? Thanks

**Comment by WickyNilliams** [comment]
I don't have the time to look into it properly. But inspecting their page with dev tools I see that they are in fact using headroom (or more likely, the ReactJS implementation of it). So it should be possible. Going to close this issue

**Comment by nickpoulos** [comment]
@dangelion ever have any luck figuring out this issue? @WickyNilliams is right in that it is the reactJS implementation, but it has some customization stuff that other implementations might not, such as 'disableInlineStyles', which would allow us to achieve the effect you are talking about. But with inline styles always on, it is difficult.
