### ISSUE TITLE
Just won't work

### ISSUE THREAD

**Issue by cbnnexus** [WickyNilliams/headroom.js#274]
I've spent hours trying to get this to work to no avail. I've poured over the instructions, examples across the web, the play area, and sifted through comments... I've written my own styles, copied from other's, and even just copied the example sites. When implementing into my own, it just won't fly. No js errors, just... nothing. It seems that many others have the same issue, or spend even more hours before they finally get it to work. Maybe better documentation? I know you bolded the sentence about styles, but I'm not sure that's cutting it for most people.

**Comment by WickyNilliams** [comment]
I see you edited your comment to be less rude.

So firstly, let me explain some etiquette. As the license states, this is software is provided as-is. If it doesn't suit your usage, or has bugs, or anything, then don't use it. You're not obliged to. But *especially* don't come here and be rude - it doesn't help your case and it won't encourage myself (or any maintainer, of any repo) to help you.

Secondly, this is not how bugs should be reported. If you want prompt, polite help, you should include relevant details in the report. Essential details would include: which browser(s) are affected, whether you're using the vanilla JS, jquery, or angular versions, which release of the lib etc. A reduced test-case in code would be a massive help. A link to a reproducible live web page (codepen or jsfiddle or whatever) would be better. I cannot diagnose or help you with what you have given me, and I'm not going to chase you up about it - Github issues aren't supposed to act like a publicly-writable todo list for maintainers.

Finally, I suspect this isn't a bug, but an issue your end. The documentation site itself uses the lib, as do many other sites - so it obviously works! The docs contains all the HTML, CSS, and JS snippets you need to use. With this in mind, you would likely get better/quicker help on StackOverflow - I cannot commit time to answer people's personal requests for help. I barely have time to read/fix actual bugs! If you come back with a proper report that demonstrates it's clearly a bug, then I will endeavour to help. 

In any case, hope you have a good day. Closing for now

**Comment by cbnnexus** [comment]
Apologies, I didn't mean to be rude. It's a suggestion to add more and/or better documentation, and an acknowledgement that others have had the same problem. At this point I think you have written more words responding to people complaining about documentation or setup problems than you have in your actual documentation. :) <- that's a joke, no need to run to a safe space - couldn't help it... you tend to go on about people's "tones" in other threads. :)

I understand the time constraints. That's why I've moved on to other options. Thanks for taking the time to respond!

**Comment by WickyNilliams** [comment]
Likewise, I think you have now written more words than if you had submitted a helpful report in the first place ;) 

Anyway, here's an example of it working. CSS and JS taken directly from the docs. Only thing the docs don't explicitly mention is `position: fixed`, but I assume that is implied by the nature of the library. https://codepen.io/anon/pen/rwmGaJ?editors=0010

**Comment by cbnnexus** [comment]
Thanks!

**Comment by cbnnexus** [comment]
I've used the example you sent and set it up exactly as indicated. Still doesn't work... no js errors. At this point I'm thinking there's some sort of override going on with other JS on the page... will start removing and seeing what happens.

**Comment by cbnnexus** [comment]
Got it working by copying the contents of  https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.3/headroom.min.js. Overall, it has 599 differences from 443 lines of code with the headroom.js I was using from the downloaded version from GitHub. Interesting.

**Comment by WickyNilliams** [comment]
Hmm... did you perhaps take the Headroom.js file from the `src/` dir rather than the `dist/` dir? Sounds like it might be the case

**Comment by WickyNilliams** [comment]
I would recommend always grabbing from here: https://unpkg.com/headroom.js, as that will give you the latest version from npm (see README: https://github.com/WickyNilliams/headroom.js#using-headroomjs-with-a-cdn).

**Comment by cbnnexus** [comment]
Yes, I'm sure that's what I did, or something similar. I should have started a barebones site with it first instead of trying to integrate it into my existing site. I would have come to that conclusion faster, I think. I'm used to downloading a latest version or a file with one version and I'm sure src made sense to me. But you know what they say about hindsight. Anyway, thanks for your replies!

**Comment by WickyNilliams** [comment]
Cool! Glad to hear it was something as simple as that. So you now have it working with your site?

As an aside: producing a reduced test-case for this issue would have also helped you get to the bottom of it :)
