### ISSUE TITLE
headroom js not working with pagepiling

### ISSUE THREAD

**Issue by peterlunglum** [WickyNilliams/headroom.js#275]
I'm having trouble getting headroom to work. I'm trying to build a site using pagepiling js, but for some reason, headroom doesn't animate the header. Is there a problem with headroom when used in relation with pagepiling that I'm not seeing? I've attached the file I'm currently working with. 

[WIP.zip](https://github.com/WickyNilliams/headroom.js/files/1116761/WIP.zip)

**Comment by WickyNilliams** [comment]
I guess that pagepiling is hijacking scroll, so that no scroll events are fired. In which case, they may be incompatible.
