### ISSUE TITLE
Way to destroy or unbind headroom

### ISSUE THREAD

**Issue by sethstha** [WickyNilliams/headroom.js#277]
I am using `window.matchMedia` to only make header sticky on the desktop.
As It is using the same class. It is also happening on mobile. 

Is there any way to destroy it in certain window width?

Thanks

**Comment by WickyNilliams** [comment]
Something like this should work, I think:

```js
var mql = matchMedia("(min-width:60em)");
var hr = new Headroom(document.querySelector("header"));

function handleChange(mq) {
  if(mq.matches) {
    hr.init();
  }
  else {
    hr.destroy();
  }
}

handleChange(mql);
mql.addListener(handleChange);
```
