### ISSUE TITLE
Scrolling slowly doesn't trigger change

### ISSUE THREAD

**Issue by rijkvanzanten** [WickyNilliams/headroom.js#279]
## Info
Version: 0.9.4

## Expected behavior
Setting tolerance to 10 should trigger state change after scrolling 10px

## Actual behavior
When scrolling slowly, the state doesn't change

Demo:
https://codepen.io/RijkvanZanten/pen/NgJmZg

**Comment by WickyNilliams** [comment]
I think the docs explain this badly. Tolerance is not amount of pixels scrolled, but the speed of scroll measured in pixels per frame. This is intentional as it allows for slow scrolling upwards (e.g. to re-read a section) without revealing the header. Hope that helps.

**Comment by rijkvanzanten** [comment]
Ahhh okay, that explains. Thanks!
