### ISSUE TITLE
bower install this to 404

### ISSUE THREAD

**Issue by gaoyia** [WickyNilliams/headroom.js#280]

**Comment by bootsified** [comment]
Yup...  Same here.

```
bower install https://unpkg.com/headroom.js/bower.zip --save-dev
bower not-cached    https://unpkg.com/headroom.js/bower.zip#*
bower resolve       https://unpkg.com/headroom.js/bower.zip#*
bower download      https://unpkg.com/headroom.js/bower.zip
bower EHTTP         Status code of 404
```

**Comment by henriquecholo** [comment]
Same here

**Comment by WickyNilliams** [comment]
Crap, looks like I forgot to update the readme after unpkg dropped full bower support... Can you try this:

```
bower install https://unpkg.com/headroom.js
```

or if you want a specific version:

```
bower install https://unpkg.com/headroom.js@0.9.4
```

If that works for you, i'll update the docs to explain that. Cheers

**Comment by bootsified** [comment]
Seems to work, but it looks like that package doesn't include the jQuery helper file.  🤔  
![screen shot 2017-09-01 at fri sep 1 2017 3 11 35 pm](https://user-images.githubusercontent.com/1693606/29986211-07da0104-8f28-11e7-96d2-f40711b2de2c.png)

**Comment by smety** [comment]
I have same problem :-/

**Comment by WickyNilliams** [comment]
You should be able to include the jquery helper with the following:

```bash
bower install https://unpkg.com/headroom.js@0.9.4/dist/jQuery.headroom.js
```

**Comment by mirkavolakova** [comment]
Getting `bower ENORESTARGET  URL sources can't resolve targets` when running [the last command](https://github.com/WickyNilliams/headroom.js/issues/280#issuecomment-326932067).

**Comment by nbonamy** [comment]
Hello. Has anybody found a way to install properly through bower?

Thanks,
Nicolas

**Comment by netfly** [comment]
unfortunally not .... same problem here

**Comment by adampatterson** [comment]
I previously had the same issue, and the fix no longer works or maybe I never had it working.

BUT,

`bower install headroom.js --save` does work, but it's  0.9.3, not the latest 0.9.4

**Comment by reco** [comment]
please fixxxx :(

**Comment by faisalferoz** [comment]
Install using `bower install https://registry.npmjs.org/headroom.js/-/headroom.js-0.9.4.tgz --save`

**Comment by WickyNilliams** [comment]
I'm giving up on bower support. It requires too much effort on my part, and doesn't align with conventions established in the rest of the ecosystem. Also, it is effectively a dead project. 

Apologies, but I am closing for that reason

**Comment by bootsified** [comment]
Understood. Times have definitely changed. Cheers! 🍻

**Comment by adampatterson** [comment]
> I'm giving up on bower support. It requires too much effort on my part and doesn't align with conventions established in the rest of the ecosystem. Also, it is effectively a dead project.
> 
> Apologies, but I am closing for that reason

Sad...  It's not you at all, but Node or needing to use Webpack or ES6 imports, or uploading an entire node modules folder kinda sucks when you can simply include a dist file from a bower repo and move on with your life. Never needing to maintain a constantly changing Webpack/Babel stack.

**Comment by hacknug** [comment]
The npm release has always (or at least for as long as I can remember/used this library) included all of the files you might need. So as long as you can install a dependency and manually move whatever file from `dist` you need to another folder, this shouldn't be a deal breaker for many.

**Comment by WickyNilliams** [comment]
@adampatterson I agree, the premise of bower was very attractive. But alas, the ecosystem has moved on with ES modules, Node, webpack etc. 

Are you completely prevented from using this library with bower as it stands?

As @hacknug pointed out, i _only_ publish the `dist` files to npm, no source files, so you shouldn't need any bundler or anything like that to consume. There is no plan to change this aspect of the project

**Comment by adampatterson** [comment]
@WickyNilliams No, I used `bower install https://unpkg.com/headroom.js@0.9.4/dist/jQuery.headroom.js` Holding on for dear life :)
