### ISSUE TITLE
re initializing after destroy callback doesn't work

### ISSUE THREAD

**Issue by sethstha** [WickyNilliams/headroom.js#282]
What I did is first I destroyed the headroom and then initialized it. The classes are there but I can't get the callback to work.

Also, headroom was once initialized on the desktop and I am trying to destroy it in mobile and run it once again.

Have a look at the code. I have changed the code as my code has functions which won't give you a clear idea.

```
$( '.site-header').headroom( 'destroy' );

$( '.site-header').headroom({
	tolerance: {
		down: 15
	},
	onUnpin: function() {
		$( '.site-header').css( 'transform', 'translateY(20px)');
	},
	onPin: function() {
		$( '.site-header').css( 'transform', 'translateY(40px)');
	},
	onTop: function() {
		$( '.site-header').css( 'transform', 'translateY(100px)');
	}
});	
```

Thanks, 🥇 Great plugin

**Comment by WickyNilliams** [comment]
try the solution described here: https://github.com/WickyNilliams/headroom.js/issues/130

**Comment by sethstha** [comment]
@WickyNilliams 

If you look at my code I am using `.headroom('destroy')` which now removes the data. Which is already said on `jQuery.headroom.js`
```
if(option === 'destroy'){
  $this.removeData('headroom');
}
```

I apologize for the wrong title.  Headroom initializes successfully and also the class names are being added on the scroll but callback function like `onPin` and `onTop` are not working. You can try to reproduce with the given code above.

**Comment by WickyNilliams** [comment]
So it does, didn't even realise I'd fixed that bug 😆 I don't have time to reproduce, could you create a test case and post a link here?

**Comment by sethstha** [comment]
Hi @WickyNilliams 

Here is the test case I made on codepen https://codepen.io/sethstha/pen/rzrZOY

You can have a look there.

**Comment by sethstha** [comment]
Found a workaround

Checking if it header has headroom class or not and destroying it saves the all the mess here.

```
if( $('.site-header').hasClass( 'headroom' ) ) {
   $('.side-header').headroom('destroy');
}
```
