### ISSUE TITLE
Possible to trigger headroom--top earlier?

### ISSUE THREAD

**Issue by alexhollender** [WickyNilliams/headroom.js#283]
Hey, this is a question not an issue:

I'm wondering, when scrolling up towards the top of the page, if it's possible to trigger `headroom--top` earlier than the actual top of the screen? For the specific use case I've got it'd be great if I could do that.

Thanks so much!

**Comment by WickyNilliams** [comment]
The `offset` option should do this

**Comment by WickyNilliams** [comment]
Eg. Setting offset to 200 will trigger top at 200px from top

**Comment by alexhollender** [comment]
Sorry didn't have notifications turned on. Thank you very much!

**Comment by alexhollender** [comment]
Ok, can't seem to get the `offset` to work. Should it look like this?

```
headroom.init({ 
		"tolerance": 1,
		"offset": 300,
	});
```
