### ISSUE TITLE
beginner questions

### ISSUE THREAD

**Issue by andrearicci** [WickyNilliams/headroom.js#284]
`var myElement = document.querySelector("header");` is referring an html5 header or a object named id="header"?
That's because I have a `<header id="top">` in my code, shall I refer to it as "header" or "top"?

Where in the html shall I put the plain JS call? Is it in the head? Before or after my `<header>`? at the bottom?
I could'nt find it in the samples.

Thank you, and sorry for my ignorance.

**Comment by alexhollender** [comment]
That is referring to a header element (i.e. `<header>`). If you wanted to refer to the element with an id of top you would use `var myElement = document.querySelector("#top");`
