### ISSUE TITLE
`this` is undefined

### ISSUE THREAD

**Issue by LucaRosaldi** [WickyNilliams/headroom.js#287]
Hello,

when using a normal `<script>` for including Headroom.js in a webpage, the factory function fails to assign the variable to the global object, because `'use strict'` statement sets `this` to `undefined` instead of `window`.

A workaround would be to use directly the `window` var instead of `this`, as it is only used when including the script directly.

**Comment by WickyNilliams** [comment]
This shouldn't be a problem any longer as I'm using rollup to generate UMD build, rather than something custom, as I had before
