### ISSUE TITLE
Doesnt work scrollerElement

### ISSUE THREAD

**Issue by nikoviedo** [WickyNilliams/headroom.js#290]
Hey! hi! I use the latest version of plugin.
I've three columns like a boxes with scrollable content, like a swiper app.
- Is a headroom for element?

**Comment by mattialori** [comment]
Same problem, scroller seems to be ignored

**Comment by ben-roth** [comment]
likewise, is it possible to set a parent container as the scrolling element instead of the body?

**Comment by WickyNilliams** [comment]
It works, here's an example where the scroller is something other than `window` https://codepen.io/WickyNilliams/pen/zgQQjy?editors=0110
