### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by neiltomlow** [WickyNilliams/headroom.js#292]
Hi, 
I've headroom.js in a WP theme. Now I want to add a post grid on a page, but headroom.js seems to block this. I've got this error:
> plugins.js?ver=4.9:44 Uncaught TypeError: Cannot read property 'add' of undefined
>     at e.init (plugins.js?ver=4.9:44)
>     at headroom.js?ver=4.9:5
> init @ plugins.js?ver=4.9:44
> (anonymous) @ headroom.js?ver=4.9:5

You can find it on this webpage: http://klanten.bureautint.nl/red/test-page/.

Please help...

**Comment by calebmichaelsanchez** [comment]
You ever find a solution to this? I'm dealing with a similar problem.

**Comment by OlegFilth** [comment]
when requires with browserify I have error like this `bundle.js?ver=1.0.0:1 Uncaught TypeError: Cannot read property 'unslick' of undefined at m.fn.init.t.fn.slick (bundle.js?ver=1.0.0:1)`

**Comment by jrondorf** [comment]
Try to add the initialisation code into 

http://learn.jquery.com/using-jquery-core/document-ready/

**Comment by coder618** [comment]
> edit: The element I was passing to the Headroom constructor a properjs object. Had to append a [0] to the element.

Thanks man, its working but why i have to parse [0], when there is only one item in the dom

**Comment by WickyNilliams** [comment]
Are you using querySelectorAll? This always returns an array, even if there's a single matching item. Try querySelector instead
