### ISSUE TITLE
not able to destroy the headroom in match function using enquire.js

### ISSUE THREAD

**Issue by gt06** [WickyNilliams/headroom.js#294]
Thanks for the great plugin.

I have implemented headroom in the project. On desktop, it works fine. I want to disable the headroom for less than 767px using enquire.js.

I have to implement but not able to disable.
headroom implementation is in main.js and disables the headroom script I have placed in the head tag.
`
enquire.register('screen and (max-width:767px)', {
        match: function () {
			alert('matched');
			var header = document.querySelector(".site-header");
			var headroom = new Headroom(header, {
				offset : 40,
				tolerance : {
						up : 5,
						down : 0
					},
				onPin : function() {
							jQuery('body').addClass("header--pinned");
							headerRelease();
						},
				onUnpin : function() {
							if (window.location.href.match("/checkout/cart/")) {
								jQuery('body').addClass("header--pinned");
								headerRelease();
							}else {
								jQuery('body').removeClass("header--pinned");
								headerFixed();
							}
						},
				onTop : function() {
						  jQuery('body').removeClass("header--pinned");
						  headerRelease();
						}
			});
			headroom.destroy();
        },
    
        unmatch: function () { 
            var header = document.querySelector(".site-header");
			var headroom = new Headroom(header, {
				offset : 40,
				tolerance : {
						up : 5,
						down : 0
					},
				onPin : function() {
							jQuery('body').addClass("header--pinned");
							headerRelease();
						},
				onUnpin : function() {
							if (window.location.href.match("/checkout/cart/")) {
								jQuery('body').addClass("header--pinned");
								headerRelease();
							}else {
								jQuery('body').removeClass("header--pinned");
								headerFixed();
							}
						},
				onTop : function() {
						  jQuery('body').removeClass("header--pinned");
						  headerRelease();
						}
			});
			headroom.init();
        }
    })
`

**Comment by hacknug** [comment]
Have you tried with `window.matchMedia`?

I'm using it like this and I have no issues with it:

```js
const mqL = window.matchMedia('(min-width: 1366px)')

var headerElement = document.querySelector('#main-header')
var headroom = new Headroom(headerElement, {
  offset: 0,
  tolerance: 5,
  classes: {
    initial: 'transition-150',
    unpinned: 'translate-y--100'
  }
})

var headroomHeader = function () {
  if (mqL.matches) {
    headroom.destroy()
  } else {
    headroom.init()
  }
}
mqL.addListener(headroomHeader)
headroomHeader()
```

**Comment by asifmohtesham** [comment]
> 
> 
> Have you tried with `window.matchMedia`?
> 
> I'm using it like this and I have no issues with it:
> 
> ```js
> const mqL = window.matchMedia('(min-width: 1366px)')
> 
> var headerElement = document.querySelector('#main-header')
> var headroom = new Headroom(headerElement, {
>   offset: 0,
>   tolerance: 5,
>   classes: {
>     initial: 'transition-150',
>     unpinned: 'translate-y--100'
>   }
> })
> 
> var headroomHeader = function () {
>   if (mqL.matches) {
>     headroom.destroy()
>   } else {
>     headroom.init()
>   }
> }
> mqL.addListener(headroomHeader)
> headroomHeader()
> ```

@hacknug,
Appreciate your assistance, all the `headroom--[...]` classes are removed when the `destroy()` method is called. However, they are added to the `<header>` as soon as we scroll. What do we do to prevent this from happening? Where am I wrong?
Here's the entirety of my code:

`export const
sm = "(min-width: 576px)",
md = "(min-width: 768px)",
lg = "(min-width: 992px)",
xl = "(min-width: 1200px)";`

`import { md } from "./variables.js";`

`class Header() {
	window.addEventListener("DOMContentLoaded", () => this.initialise_headroom());
	window.addEventListener("resize", event => this.initialise_headroom(event.target.outerWidth));`

	initialise_headroom(width) {
		const mobile_header = document.querySelector("#mobile-header"), mqmd = window.matchMedia(md);
		var mobile_header_hr = new Headroom(mobile_header, {
			offset: 50,
		});
		let hr = () => {
			if( !mqmd.matches || !window.matchMedia("(min-width: " + width + "px)").matches ) {
				mobile_header_hr.init();
			} else {
				mobile_header_hr.destroy();
			}
		}
		mqmd.addListener(hr);
		hr();
	}
`}`

Thank you for your time! :-)

**Comment by asifmohtesham** [comment]
@hacknug, I must be a special kind of stupid. I came here to delete the comment (_because I figured where I messed_) to save myself some embarrassment. But, it seems I am little too late. :-P
Thank you! ;-)

**Comment by hacknug** [comment]
Don’t sweat it! We’re all learning new things everyday haha
