### ISSUE TITLE
Add a class when page end (bottom) is reached when scrolling down

### ISSUE THREAD

**Issue by timashev** [WickyNilliams/headroom.js#295]
While playing with Headroom.js I've got an idea of showing all the navigational elements not only when scrolling up, but also when the user reaches the end of the page. First I thought the `"classes": { "bottom": ... }` option will work, but it appeared it is intended for something else (like bottom navbar maybe).

Could you please add this feature?

**Comment by scsskid** [comment]
I guess this was already added? because `.headroom--bottom` is added when reaching the bottom, unfortunately you dont have an offset option here

**Comment by WickyNilliams** [comment]
@timashev that's exactly what should happen. The `bottom` class is added when scrolled all the way to the bottom of the page. You have two options to do what you want.

First in CSS:

```css
.headroom--pinned,
.headroom-bottom {
  /* your styles here */
}
```

Or, in JS:

```js
const headroom = new Headroom(elem, {
  bottom: "headroom--pinned"
});
```

That should then bring the header back in when at the bottom. Hope that helps
