### ISSUE TITLE
Methods to hide/unhide

### ISSUE THREAD

**Issue by anteksiler** [WickyNilliams/headroom.js#296]
I think it would be great to have methods for more complex functionalities.

**Comment by thisbailiwick** [comment]
I used something like this to pin and unpin manually. Based on your issue title I think this may be what you're looking for.
Your comment seems to be looking for more.


`function custom_pin_header() {
    headroom.__proto__.pin.call(headroom);
}

function custom_unpin_header() {
    headroom.__proto__.unpin.call(headroom);
 }`

**Comment by WickyNilliams** [comment]
or just call `someHeadroomInstance.pin()`

**Comment by hacknug** [comment]
@WickyNilliams maybe we should add a Methods section to the README mentioning this and other undocumented methods?

**Comment by WickyNilliams** [comment]
Great idea. There's an open issue about adding one thing to the docs, I'll expand its scope to include all documentation changes that come about as a result of cleaning up house.
