### ISSUE TITLE
Pin/unpin, then tolerance only for page scroll

### ISSUE THREAD

**Issue by TheMangoTrain** [WickyNilliams/headroom.js#298]
Hello

Is there a way to specify tolerance _only_ for page scrolling? Currently, when you specify tolerance, the effect applies to everything (header and page), however I'd like to pin/unpin the header as per usual (ie instantly; no tolerance) meanwhile have a tolerance value only affect scrolling of the actual page content.

Put another way: On a single swipe, short or medium, the user see's the header pin/unpin accordingly. If they continued to swipe long, or on their second swipe (in the same direction), only then the actual entire page would scroll.

Basically a bias towards pin/unpin the header _first_, then when enough scrolling has happened, or on additional scrolling, then actually scroll the page content. A separation of events. Looking at native Android apps, you see this kind of UX.  Check out the [sample animations here](https://material.io/guidelines/patterns/scrolling-techniques.html#scrolling-techniques-app-bar-scrollable-regions).

Header.js is great, but I feel like there can be too many things happening at once (movement of header + movement of content) depending on configuration, and the user may lose their point of reference in the content they were looking at.

**Comment by WickyNilliams** [comment]
Headroom.js does not support this at the moment. Maybe in future. But I will close for now
