### ISSUE TITLE
Not trigger when clicking on anchors?

### ISSUE THREAD

**Issue by patrick-minton** [WickyNilliams/headroom.js#300]
If a user clicks on an anchor link such as:

```
<a href="#myAnchor">Go to top</a>
```

If the anchor is "above" the user's position, The browser "scrolls", and the header will get the `--pinned` class. The problem is that if you use `--pinned` to apply fixed positioning, your `headroom` class is now above/on top of the anchor that the user just scrolled to.

Is there a way around this?

**Comment by lextoc** [comment]
Excellent question, I've just stumbled upon the same problem. Ideally we could "freeze" the headroom functionality so we've control over when to show the (e.g.) navigation bar and when not when going up.

**Comment by hacknug** [comment]
Not the most bulletproof solution due to browser support but I think you could use [`scroll-padding`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding) to fix it.

**Comment by WickyNilliams** [comment]
That seems like the ideal solution to me

**Comment by WickyNilliams** [comment]
I will add a mention of this in the docs. See #323

**Comment by lextoc** [comment]
Doesn't seem like the ideal solution to me but certainly worth mentioning, thanks for the help. Love this widget! ❤️

**Comment by WickyNilliams** [comment]
@lextoc why does it not seem ideal to you? And thanks :)

**Comment by WickyNilliams** [comment]
I forgot to mention, I've merged a PR relating to freezing the functionality of the lib, it just needs releasing. I hope this will meet your needs if you don't like the `scroll-padding` approach

**Comment by lextoc** [comment]
> I forgot to mention, I've merged a PR relating to freezing the functionality of the lib, it just needs releasing. I hope this will meet your needs if you don't like the `scroll-padding` approach

Great!!!! You're the best!!!
