### ISSUE TITLE
WordPress integration

### ISSUE THREAD

**Issue by pako69** [WickyNilliams/headroom.js#302]
Hi and thank you for this wonderfull plugin.

I use it on a WordPress website (not visible because under developpement).

WordPress loads jQuery in the `<head>` and I load your jQuery version in the footer.

What I would like is two hide and reveal 2 elements instead of 1. 

The first is a `<header>` with the class .site-header
The other is a hamburger button DIV with the class .sfm-navicon-button

Well it works, but if I navigate to another page, then come back to the previous page, the hamburger button lost your CSS classes "headroom--unpinned, headroom--pinned, .headroom", so it stop to be animated.

Below is the script I'm using in the footer, and if could help me I'll give you an access to this website?

Thanks.

```
(function($) {

  if(!$) {
    return;
  }

  ////////////
  // Plugin //
  ////////////

  $.fn.headroom = function(option) {
    return this.each(function() {
      var $this   = $(this),
        data      = $this.data('headroom'),
        options   = typeof option === 'object' && option;

      options = $.extend(true, {}, Headroom.options, options);

      if (!data) {
        data = new Headroom(this, options);
        data.init();
        $this.data('headroom', data);
      }
      if (typeof option === 'string') {
        data[option]();

        if(option === 'destroy'){
          $this.removeData('headroom');
        }
      }
    });
  };

  //////////////
  // Data API //
  //////////////

  $('[data-headroom]').each(function() {
    var $this = $(this);
    $this.headroom($this.data());
  });



  ////////////
  // MY WEBSITE //
  ////////////
  $(document).ready(function() {
  
    $('.site-header, .sfm-navicon-button').headroom({
      'offset': 64,
      'tolerance': 0
    })

  });



}(window.Zepto || window.jQuery));

/*!
 * headroom.js v0.9.4 - Give your page some headroom. Hide your header until you need it
 * Copyright (c) 2017 Nick Williams - http://wicky.nillia.ms/headroom.js
 * License: MIT
 */

!function(a,b){"use strict";"function"==typeof define&.................... etc. etc.

```

**Comment by WickyNilliams** [comment]
This is as i would expect. When navigating between pages all state is lost.
