### ISSUE TITLE
Offset: different values for up and down. Same as tolerance, but for offset

### ISSUE THREAD

**Issue by JiveDig** [WickyNilliams/headroom.js#303]
This would be super useful for my use-case. I'm using CSS `position: sticky;` and don't want any fixed/hiding/animation for the header when scrolling down from the top of the window. Only going back up. When going back up I don't want any jump to fixed, only to let position: sticky; do its thing.

Regardless of my specific scenario, it may prove more flexible to allow different values for up vs down scrolling.

**Comment by proov** [comment]
I agree, for sticky elements, usually we want to unstick them before reaching the end of the page.

**Comment by JiveDig** [comment]
Unfortunately no. I ended up replacing Headroom with ScrollMagic actually. I was able to do the headroom effect plus other stuff I needed with one library. Headroom is still great, so no issues, but wasn't what I needed anymore.

**Comment by sunnyt7** [comment]
Ah. Any chance you could share a link of where you achieved the Headroom effect with ScrollMagic?

To stop that top of window hiding animation, I just tried implementing some jquery where it adds an additional class if the header is within the top X pixels of the page. The class sets the header to position: relative as opposed to position: sticky. It almost worked great, other than the fact that if you scroll too fast, you still catch the last part of the animation, so it seems like it's a no go. Curious to see how you implemented it with ScrollMagic.

**Comment by JiveDig** [comment]
Not sure how long we'll keep it like that, but I implemented it in our WordPress theme [Mai Theme](https://maitheme.com), and you can see it in action at https://bizbudding.com/

**Comment by JiveDig** [comment]
I also used it for the shrink logo, parallax, and some other stuff.

**Comment by sunnyt7** [comment]
Ah cool, thanks! I'll need to learn ScrollMagic, but for now I finally accomplished (I think) what I was going for: https://www.lawnscapes.ca/. Only took several hours 😞

**Comment by JiveDig** [comment]
Just reporting back... but first, I wanna say that Headroom is focused a great still. ScrollMagic is super powerful, but felt a bit much. I've since found basicScroll and am really happy with hit. I was also able to get it to do the Headroom thing https://codepen.io/JiveDig/pen/yZdyXM

**Comment by sunnyt7** [comment]
@WickyNilliams I saw you mention that there was a PR for this feature, but it hasn't been implemented yet correct?
