### ISSUE TITLE
Not listening to scroll event / not adding classes at all

### ISSUE THREAD

**Issue by SultanDino** [WickyNilliams/headroom.js#306]
Guys, do you have the same issue?
Headroom is initialized, but classes are not being added to the element when scrolling.

**Comment by vegardjo** [comment]
It could be you did the same as me, using the files directly from the repo? It needs to be built first, or just get the production ready file from http://wicky.nillia.ms/headroom.js/ (one of the red buttons)

**Comment by WickyNilliams** [comment]
I assume this was an issue on your end, as the library continues to work elsewhere. Closing for that reason
