### ISSUE TITLE
Vue.js Support

### ISSUE THREAD

**Issue by Nirajn2311** [WickyNilliams/headroom.js#310]
Any thoughts on making a Vue component?

**Comment by CharlesKumar** [comment]
[vue-headroom](https://github.com/dalphyx/vue-headroom) is working fine.
I don't think he would create a vue-component see this [thread](https://github.com/WickyNilliams/headroom.js/issues/311)

**Comment by WickyNilliams** [comment]
As I don't use vue, I would not feel comfortable writing/supporting a component.

I would recommend vue-headroom if it suits your purposes. Otherwise, I'm sure you could write a thin wrapper around this lib in vue
