### ISSUE TITLE
This library is not actively maintained. Is there an alternative to Headroom?

### ISSUE THREAD

**Issue by liquidvisual** [WickyNilliams/headroom.js#312]
It's such a vital library for websites, but I think we should all be using something that is more actively maintained. Does anyone use/know of any alternatives?

**Comment by nikkijd** [comment]
up

**Comment by WickyNilliams** [comment]
Closing, as this is not an issue/bug/feature request

**Comment by lkraav** [comment]
Duplicate of https://github.com/WickyNilliams/headroom.js/issues/311

**Comment by rokumatsumoto** [comment]
The same old headroom simplified
https://yarnpkg.com/en/package/headroom
