### ISSUE TITLE
Turn on headroom functionality on only landscape view [feature request]

### ISSUE THREAD

**Issue by CharlesKumar** [WickyNilliams/headroom.js#313]
I want to use headroom functionality only on landscape mode on a phone device. In other words i want to only Unpin on a screen which has less than 500px viewport height.

Desktop, laptop, tablet has enough room for fixed headers. If a function/hook to achieve this is provided then it would be helpful

**Comment by WickyNilliams** [comment]
Use the web's matchMedia API to selectively call headroom. If you search the issues I'm pretty sure I've given sample code for this before

**Comment by CharlesKumar** [comment]
Thanks for the quick reply and if you provide link to the sample code it would be nice.

**Comment by WickyNilliams** [comment]
Just search here. I'm on mobile and it's too much of a pain

**Comment by CharlesKumar** [comment]
```
.headroom--unpinned {
  transform: translate3d(0px, -0, 0px) !important;
}

@media (max-height: 30em) and (orientation: landscape) {
  .headroom--unpinned {
    transform: translate3d(0px, -100%, 0px) !important;
  }
}
```

can this hack be used in production. looks fine to me.

**Comment by WickyNilliams** [comment]
yeah that should work just fine

**Comment by WickyNilliams** [comment]
The only difference between that and matchMedia is that by doing that you'll still have scroll listeners on the page, which is somewhat wasteful if it's not doing anything. But functionally, it is fine

**Comment by CharlesKumar** [comment]
yeah @WickyNilliams 

> you'll still have scroll listeners on the page,

I am also thinking about that but i don't know how to provide the solution.

should i destroy and recreate headroom on every change detection. say when on a browser resize or orientation change in a phone. share the code when you find free time.

**Comment by WickyNilliams** [comment]
Here's an example, using the jQuery plugin, but just switch that for whatever code you already have https://github.com/WickyNilliams/headroom.js/issues/124#issuecomment-69625038.

I must say I take issue with you being too lazy to simply search "matchMedia" in the issues, whilst complaining in other issues that I don't have time to maintain this lib.

**Comment by WickyNilliams** [comment]
Or one with vanilla headroom https://github.com/WickyNilliams/headroom.js/issues/294#issuecomment-357749867

**Comment by CharlesKumar** [comment]
> whilst complaining in other issues that I don't have time to maintain this lib.

where did I complain?

> being too lazy to simply search "matchMedia" in the issues

I thought searches would crawl only titles. Now i learned it can bring results by searching the entire issues.

Peace bro ! No issues !
