### ISSUE TITLE
Move away from grunt, and to ES modules

### ISSUE THREAD

**Issue by WickyNilliams** [WickyNilliams/headroom.js#314]
The build system for this lib is very dated. It currently uses gruntjs and file concatenation. It would be good to:

- [x] Switch to ES modules
- [x] ~~Improve modularisation of library~~
- [x] Use something like rollup for bundling (this is preferable to webpack as it gives better bundle size for libraries)
- [x] Switch to ESLint
- [x] Update the scripts in package.json to be updated to then call rollup
- [x] Consider something like cypress for testing.
- [x] Get CI setup properly
- [x] Run prettier over repo

**Comment by WickyNilliams** [comment]
I've started on this. Got a basic build working. Just need to get uglify/terser integrated now.

After that I will look at modernising the codebase to use ES6+ features (arrows, `class` etc), and integrating babel.

**Comment by hacknug** [comment]
We should probably also migrate from jshint to eslint. We can use this to migrate the current config if you don't want to adopt of of the standards: https://github.com/brenolf/polyjuice

**Comment by WickyNilliams** [comment]
WIP PR here: #324

**Comment by WickyNilliams** [comment]
Decided to skip modularisation for now, as I'd rather this contain as few changes to `src` as possible. This can be done as a follow-up.
