### ISSUE TITLE
Problem that "onBottom" may not be fired

### ISSUE THREAD

**Issue by yutahaga** [WickyNilliams/headroom.js#315]
I encountered a problem in which `window.pageYOffset` became a floating point type and that `onBottom` did not fire.

<img width="121" alt="capture" src="https://user-images.githubusercontent.com/5030849/53685889-fc921700-3d63-11e9-83c1-a1f1f3bc30b3.png">

`pageYOffset` seems to need to be rounded off.

---

My environment
Windows 10 (64 Bit)
Chrome Version: 72.0.3626.121 (Official Build) (64 Bit)

**Comment by WickyNilliams** [comment]
Excuse the delay in responding.

Surprised this bug hadn't been spotted earlier in this project's life! MDN clearly states `pageYOffset` returns a floating point: https://developer.mozilla.org/en-US/docs/Web/API/Window/pageYOffset#Value

I will fix.
