### ISSUE TITLE
Uncaught TypeError: $(...).headroom is not a function

### ISSUE THREAD

**Issue by dimative** [WickyNilliams/headroom.js#317]
How can i fix it. I want to use it with jquery js.
jquery and headroom js already imported on my footer. 
please see this: https://codepen.io/dimative/pen/MRLqqV

**Comment by TheDigitalOrchard** [comment]
You need to load both the Headroom JavaScript AND the jQuery.Headroom plugin. These are separate files. jQuery support is only available if you load the second file.

**Comment by WickyNilliams** [comment]
That is correct, you need to add both. I forked your pen and did just that. I added some CSS to get the slide in/out behaviour, and fixed a typo in a the `js-headroom` classname: https://codepen.io/WickyNilliams/pen/EqzGjW?editors=1100
