### ISSUE TITLE
Scroller element not working

### ISSUE THREAD

**Issue by bountydigital** [WickyNilliams/headroom.js#320]
I've got this JS, but scroller element isn't recognised. Does it have to be an ID or class?

```
var main = document.querySelector("main");
var elem = document.querySelector("header");
var headroom = new Headroom(elem, {
   scroller: main,
});
headroom.init();
```

**Comment by ScootyPuffJR** [comment]
`scroller: main,` shouldn't be necessary, it default to `window` already

The `elem` var is valid, you can select `"header"`

I also had an issue with the `headroom.js` hosted here on this repo. The code is different than what's hosted on the [developer's website](http://wicky.nillia.ms/headroom.js).

[This ](https://npmcdn.com/headroom.js/dist/headroom.min.js)is the code that worked for me

**Comment by WickyNilliams** [comment]
This code looks correct to me, headroom expects you to pass in the actual node/element as you have done. I assume this must have been an issue with your HTML? Closing for now. Let me know if there are still issues
