### ISSUE TITLE
Updates to docs

### ISSUE THREAD

**Issue by WickyNilliams** [WickyNilliams/headroom.js#323]
This is an umbrella issue to cover all changes to the docs.

- [x] add section on `scroll-padding`. See #300 and #38
- [x] add section describing all methods. See #296 & #316
- [x] add instructions for installing via npm/yarn

**Comment by WickyNilliams** [comment]
I've been thinking as part of this that I'm going to remove all usage documentation from the README. The README can just contain info about the code/repo, how to build, contribute etc. Then the website will contain all the usage documentation. This avoids the duplication we have at the moment.

Does this sound like a bad idea?

**Comment by EnigmaSolved** [comment]
That sounds fine to me!
