### ISSUE TITLE
Сustom options.classes do not apply

### ISSUE THREAD

**Issue by cap-Bernardito** [WickyNilliams/headroom.js#335]
`function Headroom(elem, options) {
  options = options || {};
  Object.assign(this, Headroom.options, options);
  Object.assign(this.classes, Headroom.options.classes, options.classes);
  ...`
  this.classes == Headroom.options.classes(default options.classes), but not options.classes(custom options.classes);

**Comment by WickyNilliams** [comment]
Messed up the initial release, but this is now on npm as `v0.10.2` :)
