### ISSUE TITLE
[Bug] Offset property not work

### ISSUE THREAD

**Issue by KytoSai** [WickyNilliams/headroom.js#340]
I updated to new Headroom 0.10.2 
But property `offset` not work 

I try with 0.9.4, propery `offset` work good !

**Comment by WickyNilliams** [comment]
Can you explain how it doesn't work? And give some code which will show this?

**Comment by WickyNilliams** [comment]
I just created a codepen using latest build of headroom.js and it all seems good to me: https://codepen.io/WickyNilliams/pen/zYOLbqK?editors=0010

I've set `offset` to the height of the grey area at the top. You will notice the header is always pinned within the grey area. This is as-designed. 

Maybe I've inadvertently fixed a bug that you relied on?

**Comment by KytoSai** [comment]
> I just created a codepen using latest build of headroom.js and it all seems good to me: https://codepen.io/WickyNilliams/pen/zYOLbqK?editors=0010
> 
> I've set `offset` to the height of the grey area at the top. You will notice the header is always pinned within the grey area. This is as-designed.
> 
> Maybe I've inadvertently fixed a bug that you relied on?

I checked class change. I see:

Version 0.9.4 ,class `headroom--not-top` added when scroll to `offset` . Has this behavior been changed in the latest version ?

Version 0.10.2, class `headroom--not-top` added when scroll > 1px from top

**Comment by WickyNilliams** [comment]
This should now be fixed in `v0.10.3`

**Comment by WickyNilliams** [comment]
Hey @KytoSai did this fix your issues?

**Comment by KytoSai** [comment]
It fixed. Thanks you ! ^^

**Comment by WickyNilliams** [comment]
Awesome, thanks for letting me know
