### ISSUE TITLE
website down? 

### ISSUE THREAD

**Issue by michabbb** [WickyNilliams/headroom.js#344]
![SmartSelect_20190918-092018_Medium](https://user-images.githubusercontent.com/3524595/65125515-c6fa0600-d9f5-11e9-9e37-1dbd7a74551b.jpg)

**Comment by hacknug** [comment]
Works fine for me now.

**Comment by michabbb** [comment]
yes, now it´s working 👍

**Comment by WickyNilliams** [comment]
That's weird, there must have been a temporary issue with Github Pages
