### ISSUE TITLE
Wrong yarn syntax at https://wicky.nillia.ms/headroom.js/

### ISSUE THREAD

**Issue by r3sMetz** [WickyNilliams/headroom.js#349]
Hello,

haven't found a website-repo for your great plugin, so i stick with opening an issue :)
On the Headroom website there is yarn install, not yarn add on the "Or install via npm/yarn:" section.

**Comment by WickyNilliams** [comment]
Thanks for reporting this! I just pushed a change to fix. The website is on the `gh-pages` branch btw :)
