### ISSUE TITLE
IE11 Syntax Error

### ISSUE THREAD

**Issue by clxmstaab** [WickyNilliams/headroom.js#350]
since https://github.com/WickyNilliams/headroom.js/commit/18975e19f1e647cae56a910927cb1121ef1a8149 headroom depends on Object.assign which is not available in IE11.

Is this a expected BC break? which browsers are considered supported in headroom.js?

![image](https://user-images.githubusercontent.com/47448731/66460501-5768bb00-ea77-11e9-9b1b-d80905747931.png)

In case this was a expected BC break, it would be great if it could be mentioned in the release notes on github, so people consuming the lib (e.g. via Dependabot) immediately have this information at hand

**Comment by hacknug** [comment]
It's specified on the site: http://wicky.nillia.ms/headroom.js/

**Comment by WickyNilliams** [comment]
I wasn't aware IE11 doesn't offer `Object.assign`, it wasn't an intentionally breaking change. I might reintroduce our own helper function to avoid use of `Object.assign`.

However as @hacknug pointed out, there is a browser support section on the website. It doesn't list the actual browsers that are supported, but rather the browser APIs that are used. You can then choose what to polyfill yourself. 

There is also a property on the Headroom class which will tell you if the browser is supported. You may wish to wrap your initialisation code in a conditional to avoid errors:

```js
if(Headroom.cutsTheMustard) {
  const hr = new Headroom(header);
  hr.init();
}
```

I should probably add a section to the docs explaining this, as it is currently not mentioned anywhere.

**Comment by clxmstaab** [comment]
thx for getting back to me.

> I wasn't aware IE11 doesn't offer `Object.assign`, it wasn't an intentionally breaking change. I might reintroduce our own helper function to avoid use of `Object.assign`.

we started loading a polyfill for it now, so it is not longer a problem on our end.
I just wanted to make sure you are aware of the problem.

> However as @hacknug pointed out, there is a browser support section on the website. It doesn't list the actual browsers that are supported, but rather the browser APIs that are used. You can then choose what to polyfill yourself.

thats right - I realized it, after I had to research why things broke.
just for best practice sake it would be awesome to have BC breaking news in the github release notes. I understand though, that you weren't aware of this BC break either.

> I should probably add a section to the docs explaining this, as it is currently not mentioned anywhere.

having this mentioned in the usage-instructions would be awesome.

**Comment by WickyNilliams** [comment]
I've added a note to the release here on github about the breaking change and the possible solutions. When I get to v1, I'll follow semver so hopefully this stuff will be more obvious in future.

I'll update the docs shortly to mention testing for support as described above.

Thanks for reporting this, I appreciate it

**Comment by clxmstaab** [comment]
> ```js
> if(Headroom.cutsTheMustard) {
>   const hr = new Headroom(header);
>   hr.init();
> }
> ```

for non-native english speakers `cutsTheMustard` is not very clear. it would be great you could add docs so it gets obvious.

maybe you should even consider for the v1 to rename this method into e.g. `Headroom.supported()` or similar

**Comment by WickyNilliams** [comment]
I just added a note to the docs, explaining how to test for support.

> for non-native english speakers cutsTheMustard is not very clear. it would be great you could add docs so it gets obvious.
> 
> maybe you should even consider for the v1 to rename this

I agree, I was just thinking this. I think I'll call it `isSupported`. I'll add to the roadmap
