### ISSUE TITLE
[Bug] Method `destroy()` don't work 

### ISSUE THREAD

**Issue by KytoSai** [WickyNilliams/headroom.js#353]
Version 0.10.3
I try use destroy() method, but don't work

It show error message
`Uncaught TypeError: Cannot read property 'destroy' of undefined`

Also i see instance has `destroy` method 

Demo: https://prnt.sc/pv6vg6

**Comment by jmartsch** [comment]
I can confirm this behaviour

**Comment by WickyNilliams** [comment]
If it says `Cannot read property 'destroy' of undefined` that means the variable is undefined, not the destroy method. Equivalent to this:

```
const a = undefined;
a.destroy(); // Cannot read property 'destroy' of undefined
```

This is an error in your code. Can you show a reduced test case?

**Comment by WickyNilliams** [comment]
Closing as I don't think this is a bug
