### ISSUE TITLE
0.9.4 -> 0.10.3 upgrade no longer adds top/not-top classes on init

### ISSUE THREAD

**Issue by Ambient-Impact** [WickyNilliams/headroom.js#354]
I'm not sure if this is a bug exactly, but I had a bit of a confusing issue when upgrading to the latest version in that I had ```z-index``` stuff that used different values for the Headroom-enabled element based on whether it had the top class or not, which doesn't seem to be applied anymore on init. In my case, this was an issue because it caused the Headroom element to appear on top of stuff that it shouldn't, but that was fixable by adding a CSS rule to target ```.headroom:not(.headroom--top):not(.headroom--not-top)```, i.e. when it's initialized but hasn't decided if it's at the top or not. I figured I'd share that in case someone else runs into this issue.

**Comment by flayks** [comment]
Same issue here

**Comment by WickyNilliams** [comment]
Yes I'd say this is a bug. I'll see if I can get it fixed this week

**Comment by WickyNilliams** [comment]
Fixed and released in `v0.10.4`. Let me know if you have any further issues :)

**Comment by Ambient-Impact** [comment]
[![Jenna Marbles hell yeah](https://media1.tenor.com/images/532c95ec594dc680b136c0d6528a65c1/tenor.gif?itemid=7254135)](https://tenor.com/view/hell-yeah-jenna-gif-7254135)

```0.10.4``` does seem to fix it. Thanks!
