### ISSUE TITLE
Error `Headroom is not defined` if not imported in the same file as initialised

### ISSUE THREAD

**Issue by dannyuk1982** [WickyNilliams/headroom.js#358]
I'm probably missing something obvious/doing something stupid here, but I have a `vendor.js` file and `app.js` file, using Laravel Mix to process the files and imports.

Most `import Foo from 'bar';` statements are in `vendor.js` to pull in the various packages etc. with them being used in the `app.js` where the code for the site is.

If I have in `app.js`
```
import Headroom from 'headroom.js';
var headroom = new Headroom( document.querySelector("header") );
headroom.init();
```
it all works fine. 

If I have in `vendor.js`
```
import Headroom from 'headroom.js';
```
then in `app.js` 
```
var headroom = new Headroom( document.querySelector("header") );
headroom.init();
```
then I get an error in the console
```hellotourism.js?v=1579286993:96 Uncaught ReferenceError: Headroom is not defined```

In the HTML I have 
```
  <script src="/path/to/js/vendor.js"></script>
  <script src="/path/to/js/app.js"></script>
</body>
```

I haven't run into this with anything else similar

**Comment by WickyNilliams** [comment]
Hey. That's exactly what I would expect. If imported as a module, it doesn't pollute the global scope. 

If you are using webpack or something like that you can use the code splitting feature to divide your code into two bundles. However that would probably require a lot of reworking of your code.

The alternative (somewhat hacky) approach would be to do this:

```js
import Headroom from "headroom.js";
window.Headroom = Headroom;
```

This will make it available on the global scope for use elsewhere. 

Hope that helps.

**Comment by dannyuk1982** [comment]
That works perfectly, thanks for the lightening quick reply!

**Comment by WickyNilliams** [comment]
Glad to hear it!
