### ISSUE TITLE
--pinned and --unpinned is not added in latest release(s)

### ISSUE THREAD

**Issue by dakur** [WickyNilliams/headroom.js#360]
It worked in 0.9.4, but no more – neither in 0.10.4 nor in 0.11.0. Do I miss something?

Code:
```js
import Headroom from 'headroom.js';

const menuElement = document.getElementById('menuBar');
const headroom = new Headroom(menuElement, {
	tolerance: {
		up: 50,
	},
});
headroom.init();
```
No custom class selectors, ran on `DOMContentLoaded`, `--not-top` etc. are added as they should be.

![image](https://user-images.githubusercontent.com/9862581/74815587-cc87af00-52f9-11ea-9a5b-e9c795108863.png)

**Comment by WickyNilliams** [comment]
Hmm... I'm surprised this ever worked. It is intended that you specify both `up` and `down` values when passing an object for `tolerance`. If you do that, everything should work:

```js
import Headroom from 'headroom.js';

const menuElement = document.getElementById('menuBar');
const headroom = new Headroom(menuElement, {
	tolerance: {
		up: 50,
        down: 0,
	},
});
headroom.init();
```

See a working example here: https://codepen.io/WickyNilliams/pen/zYOLbqK?editors=0010

**Comment by WickyNilliams** [comment]
I should really add some TS typings to the library to help with stuff like this.

**Comment by dakur** [comment]
I was expecting that modifying only one of those options will leave the second one to default. Thank you for clarification. TS typings would definitely prevent this. :-)
