### ISSUE TITLE
npm warns of 8 vulnerabilities when installing

### ISSUE THREAD

**Issue by prtksxna** [WickyNilliams/headroom.js#362]
```
▶ npm install headroom.js --save
+ headroom.js@0.11.0
added 1 package from 1 contributor and audited 240 packages in 3.288s
found 8 vulnerabilities (1 moderate, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details

```

**Comment by WickyNilliams** [comment]
Hmm.. that's strange since this library doesn't have any dependencies (apart from stuff for dev). They shouldn't even be installed if you're installing as a dependency yourself! Npm being a bit overzealous perhaps. 

In any case, I'll look to fix. Thanks for reporting

**Comment by WickyNilliams** [comment]
Hmmm... Just to be sure, could these be vulnerabilities in other packages you've installed? What does it say if you run `npm audit`?

**Comment by WickyNilliams** [comment]
```sh
$ npm install headroom.js --save

+ headroom.js@0.11.0
added 1 package from 1 contributor and audited 1 package in 1.24s
found 0 vulnerabilities
```

Just did a fresh install locally. No vulnerabilities reported. 

I think this has been misattributed. Closing
