### ISSUE TITLE
Prevent pinning on anchor jumps?

### ISSUE THREAD

**Issue by youngbrioche** [WickyNilliams/headroom.js#38]
Is there any way to prevent pinning on anchor jumps to a higher part of the page, so anchors don't get obstructed by a pinned header?

**Comment by mrreynolds** [comment]
Any chance on getting @acristinziani's solution merged?

**Comment by markmarijnissen** [comment]
A simple but effective hack:
```javascript
$(window).on('hashchange',function(){
		setTimeout(function(){
			headroom.unpin();
		},0);
	});
```

This is how it works:

1. First event loop: Click anchor-event
1.1 `hashchange` event (calls setTimeout for next event loop)
1.2 `scroll` event
1.3 Headroom is triggered
2. Second event loop: setTimeout
2.1 Cancels the Headroom using unpin()

**Comment by CathyMacars** [comment]
I would benefit from this as well. I tried @markmarijnissen's trick, but it didn't work.

**Comment by joeyhoer** [comment]
While this doesn't solve the issue at hand (i.e. "anchor jumps to a higher part of the page"), I also wanted to drop this here for the weary traveler.

The vanilla js version of @markmarijnissen's trick:

```js
document.addEventListener('hashchange', function(){
  setTimeout(function(){
    headroom.unpin();
  },0);
});
```

This seems to only work if you increase the timeout… I suspect a race condition with the scroll events & the debouncer (which uses requestAnimationFrame).

To hide the header when loading a page with a hash use:

```js
// Unpin header on URL fragments
if(window.location.hash) {
  header.classList.add("headroom--unpinned");
}
```

I believe @acristinziani's suggestion (possibly addressed by #253), in combination with the `hashchange` event may be a suitable solution.

**Comment by kripod** [comment]
Unfortunately, the `setTimeout` approach doesn’t play well with several popular browsers (e.g. Firefox and Safari), and react-router doesn’t fire the browser `window` ‘s `hashchange` event.

Also, I would like to always **show** the navbar rather than hiding it during scroll. Is there a way to solve this?

**Comment by WickyNilliams** [comment]
As advised [here](https://github.com/WickyNilliams/headroom.js/issues/300#issuecomment-506759819), I would consider using the standardised scroll-padding css property. This has pretty good browser support (which will only improve over time), is built exactly for this purpose, and avoids awkward JS workarounds. 

For that reason, I'm going to close. It only took 5 years to get to this point haha

**Comment by konovalov-nk** [comment]
> I would consider using the standardised scroll-padding css property. This has pretty good browser support

Unfortunately, `scroll-padding` doesn't work in Safari browser [without some tricks](https://stackoverflow.com/a/58890319/2959158). On my recent project, I've tried to make it work without success, and in the end I've had to resort to some custom plugin like `vue-scrollto`.

**Comment by davequested** [comment]
Many thanks for the library, it's fantastic. 

I'm struggling to get scroll-padding-top to work. It works if you have manually set it in the <html> tag BEFORE headroom is loaded. But if you want to work out the height of the header first then set that to the scroll-padding-top in <html> the browser ignores it. I'm guessing the browser needs to jump down to the right place in the page early on and doesn't get the updated value. 

Anyone manage to get it working where it's dynamically setting the scroll-padding-top to the height of the header?

Thanks.
