### ISSUE TITLE
Target scrolling within a div

### ISSUE THREAD

**Issue by danrichman** [WickyNilliams/headroom.js#39]
Many mobile websites have Facebook-style slidein menus and the main content div slides over to make room for those menusIn that case, the window doesn't scroll, but the main content div has a height of 100% and the content scrolls within that relatively or absolutely positioned div. (see snap.js as an example).

Is there a way to target the scrolling within a main div, rather than the window itself?

**Comment by dcworldwide** [comment]
Is this not documented?

**Comment by dcworldwide** [comment]
If this is in fact still a supported feature please include it in the readme

**Comment by WickyNilliams** [comment]
It's documented on the project site. The readme is out of sync it seems. In the near future I will likely make the website the canonical source of documentation for the lib, so use that as source of truth for now

**Comment by dcworldwide** [comment]
Sounds good. Tried out the featured. Works well. Like the API a lot

**Comment by WickyNilliams** [comment]
Good to hear!

**Comment by omikron** [comment]
I cannot get this feature to work, it throws an error;

https://codepen.io/omikron/pen/BQKaRM

`Uncaught TypeError: this.scroller.addEventListener is not a function(…)attachEvent @ headroom.js:183`

**Comment by WickyNilliams** [comment]
@omikron you must pass the actual element, not a selector, as the scroller option

**Comment by omikron** [comment]
Sorry, not sure what you mean. Any chance you cold modify the codepen to reflect that?

**Comment by omikron** [comment]
Realized my implementation with jQuery was having an issue with passing the element as a jQuery object, but moving over to pure JS it worked fine.
