### ISSUE TITLE
Blurry in pinned state

### ISSUE THREAD

**Issue by grafikbyran** [WickyNilliams/headroom.js#403]
I have an issue I cannot figure out:
When I load the page with the HeadroomJS the header menu is nice and crisp
![image](https://github.com/WickyNilliams/headroom.js/assets/145996636/f9c249a9-c793-458c-8fbe-5f05b685ee6f)

If i scroll down it is still crisp:
![image](https://github.com/WickyNilliams/headroom.js/assets/145996636/168a063b-0643-4ef5-bf07-d3fdeea13ad8)

Then if I scroll up a bit so the menu is pinned, all content inside the HeadroomJS header is blurry / out of focus:
![image](https://github.com/WickyNilliams/headroom.js/assets/145996636/2ad9224e-bee7-4bc6-a9b5-dfc8dbb7bd46)

This is built with Bricks Builder I have seen simular behaviour with Oxygen Builder - any Ideas if this is a bug or user error?

**Comment by WickyNilliams** [comment]
i'm not sure what bricks builder or oxygen builder is sorry! i imagine it is an issue their end. if you can supply a reduced tests case, or a link to the website in question i may be able to help. but i am closing this in the meanwhile
