### ISSUE TITLE
CSS documentation hints

### ISSUE THREAD

**Issue by rosslaird** [WickyNilliams/headroom.js#51]
Thanks for creating this. It works great. But I had to work on it for quite a while before I figured out that I had to add the CSS. I initially interpreted the instructions for jQuery in a literal way:

```
// simple as this!
// NOTE: init() is implicitly called with the plugin
$("# header").headroom();
```

So, that's all I did. And indeed, it was quite simple. But although I could see the classes changing on scroll, nothing happened. So, eventually I figured out that -- at least, in my case -- I had to create and add the CSS for the classes:

```
.headroom {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    transition: all .2s ease-in-out;
}
.headroom--unpinned {top: -100px;}
.headroom--pinned {top: 0;}
```

I'm not sure if the method I used is correct, or if this is supposed to work by following the "simple as this!" guideline in the docs. But it did not work out of the box for me, and if the CSS is required, maybe that could also be shown in the documentation?

**Comment by Barrytron** [comment]
I love this plugin. But EVERY time I used it I forget the jQuery.headroom.js file, or the extra css, it's really not obvious. Great plugin though

**Comment by hsquareweb** [comment]
It just took me an hour to figure out what was missing! Nice plugin, but the documentation needs to be updated and more clear.

Let me break it down for the people who might struggle with this:

1. Include jQuery.headroom.js, and headroom.min.js
2. Add your jquery 
`$(".site-header").headroom();`
3. Add css
`.headroom {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  -webkit-transition: all .2s ease-in-out;
  transition: all .2s ease-in-out;
}

.headroom--unpinned {
	top: -100px;
}

.headroom--pinned {
	top: 0;
}`

**Comment by muhammadyou** [comment]
I couldnt find it working in my angular app
