### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by ghost** [WickyNilliams/headroom.js#63]
Some weird thing happen in this case, It seems there is not syntax errors, but some way the script doesn´t work  "at all"    http://codepen.io/sp3ncer/pen/twnFI

**Comment by CathyMacars** [comment]
I'm gonna quote @calebclark, to get to an interesting issue: "I just understand it to say that I could use css classes to override default functionality". Maybe it would be interesting for this widget to work out of the box? Of course, that would require the addition of a stylesheet in the project. This would be nice and make the widget more useable in quick projects where people are using Bootstrap and stuff like that to get a (generally temporary) site/app running as quick as possible. Just a thought.

**Comment by tabish89** [comment]
@WickyNilliams I am having trouble implementing this really cool plug-in in an angular setting/environment.  I have done the following so far and cannot for the life of me figure out what is wrong with my implementation:

1. Added headroom.js
2. Added angular.headroom.js
3. Added <src script> to index.html
4. Added requirement to angularJS module
5. Added some basic CSS

``.headroom {
    will-change: transform;
    transition: transform 200ms linear;
}

.headroom--pinned {
    transform: translateY(0%);
}

.headroom--unpinned {
    transform: translateY(-100%);
}``

What am I doing wrong?  It just doesn't want to work... activate.  I scroll up/down and nothing happens...
