### ISSUE TITLE
Feature detection doesn't prevent .bind early enough

### ISSUE THREAD

**Issue by rajivm** [WickyNilliams/headroom.js#94]
In the Headroom constructor:
```
this.debouncer        = new Debouncer(this.update.bind(this));
```

Whereas the feature check doesn't occur until init:
```
if(!Headroom.cutsTheMustard) {
    return;
}
```

Proposal: move initialization of Debouncer from constructor to init

**Comment by WickyNilliams** [comment]
Closing, we can continue any dicussion in the PR
