### ISSUE TITLE
Version that allows for browserify/require.js compatibility

### ISSUE THREAD

**Issue by jeffshaver** [WickyNilliams/headroom.js#97]
Would like the ability to use browserify/require.js with headroom. This requires a couple extra lines:

```
(function(root, factory) {
  'use strict';
  if (typeof define == 'function' && define.amd) {
    /*
     * AMD. Register as an anonymous module.
     */
    define([], factory);
  } else if (typeof exports == 'object') {
    /*
     * Node and stuff
     */
    module.exports = factory();
  } else {
    /*
     * Browser globals (root is window)
     */
    root.Headroom = factory();
  }
}(this, function() {
  // All code goes here and then return Headroom.
}));
```

This would allow the use of it as a global (as it is now), in browserify and in requirejs

**Comment by WickyNilliams** [comment]
FINALLY DONE THIS. Added UMD support and merged to master

Can someone test, with requirejs or browserify before I tag and release (I don't have time right now, trying to get through as many issues as possible)?

**Comment by WickyNilliams** [comment]
NOTE: you'll need to build locally to get changes, I tend not to update files in dist until a version has been tagged (because people will just grab latest from there, rather than latest tagged release)

**Comment by pughpugh** [comment]
Built, installed with node and required with Webpack/CommonJS. Works great, thanks. Top work!

**Comment by mttschltz** [comment]
It's working with Browserify :) Thanks!

**Comment by antoniobrandao** [comment]
The package seems to have been unpublished from NPM. Could you please restore it?

**Comment by asharma93** [comment]
+1

**Comment by asharma93** [comment]
Trying to get this working with requireJS and failing terribly. When I check the network tab, headroom.js is being pulled in fine. I'm throwing up a view that initializes headroom.js, then I'm getting the good old 'undefined is not a function'. 

My guess, headroom.js isn't returning correctly, thus loosing reference to itself. Anyone had this issue?.

**Comment by yumyo** [comment]
+1 Any plan to accept the pull / write your own ?
